version: 1.0

environments:
  local:
    description: "Core runtime + testing + autogen"
    tasks:
      - autus_server
      - autus_work
      - pytest
      - autus_autogen

  cursor:
    description: "Meta-development (셀/팩 생성)"
    tasks:
      - cell_editing
      - pack_refactor
      - autogen_preview

  vscode:
    description: "UI/Docs/3D visualization"
    tasks:
      - docs_edit
      - ui_shell
      - schema_view

