"""
═══════════════════════════════════════════════════════════════════════════════
AUTUS - 도메인 로직 120개 (Layer 2)
═══════════════════════════════════════════════════════════════════════════════

산업/부서별 고유 프로세스
카테고리: FINANCE, HR, SALES, MARKETING, IT, OPERATIONS, LEGAL, SUPPORT
"""

from .models import TaskDefinition, TaskLayer, UserType

# ═══════════════════════════════════════════════════════════════════════════════
# 도메인 로직 120개 정의
# ═══════════════════════════════════════════════════════════════════════════════

DOMAIN_LOGIC_120: list[TaskDefinition] = [
    
    # ─────────────────────────────────────────────────────────────────────────
    # 재무 도메인 (FINANCE) - 20개
    # ─────────────────────────────────────────────────────────────────────────
    TaskDefinition(
        task_id="L2_FIN_001",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="INVOICE",
        name_en="Invoice Generation",
        name_ko="송장 생성",
        description="고객 송장 자동 생성. K 낮으면 예산 알림 추가.",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=85,
        energy_cost=1.2,
        external_tool="quickbooks",
        enabled_types=[UserType.INDIVIDUAL, UserType.SMALL_TEAM, UserType.SMB, UserType.ENTERPRISE]
    ),
    TaskDefinition(
        task_id="L2_FIN_002",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="INVOICE",
        name_en="Invoice Validation",
        name_ko="송장 검증",
        description="송장 데이터 정합성 검증",
        base_k=1.1, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.8,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_FIN_003",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="PAYMENT",
        name_en="Payment Processing",
        name_ko="결제 처리",
        description="결제 트랜잭션 처리",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=1.0,
        external_tool="stripe"
    ),
    TaskDefinition(
        task_id="L2_FIN_004",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="PAYMENT",
        name_en="Payment Reconciliation",
        name_ko="결제 대사",
        description="결제 내역 대사 및 정산",
        base_k=0.8, base_i=0.0, base_r=0.0,
        automation_level=80,
        energy_cost=1.5,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_FIN_005",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="EXPENSE",
        name_en="Expense Report",
        name_ko="경비 보고서",
        description="경비 보고서 생성 및 승인",
        base_k=0.7, base_i=0.2, base_r=0.0,
        automation_level=75,
        energy_cost=1.0,
        external_tool="expensify"
    ),
    TaskDefinition(
        task_id="L2_FIN_006",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="EXPENSE",
        name_en="Expense Approval",
        name_ko="경비 승인",
        description="경비 승인 워크플로. I 음수 시 지연 방지.",
        base_k=0.8, base_i=0.3, base_r=0.0,
        automation_level=70,
        energy_cost=0.8,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_FIN_007",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="BUDGET",
        name_en="Budget Planning",
        name_ko="예산 계획",
        description="예산 수립 및 배분",
        base_k=0.6, base_i=0.2, base_r=0.0,
        automation_level=60,
        energy_cost=2.0,
        external_tool="databricks",
        enabled_types=[UserType.SMB, UserType.ENTERPRISE, UserType.NATION]
    ),
    TaskDefinition(
        task_id="L2_FIN_008",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="BUDGET",
        name_en="Budget Tracking",
        name_ko="예산 추적",
        description="예산 소진율 모니터링",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.6,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_FIN_009",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="TAX",
        name_en="Tax Calculation",
        name_ko="세금 계산",
        description="세금 자동 계산",
        base_k=1.2, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.8,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_FIN_010",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="TAX",
        name_en="Tax Filing",
        name_ko="세금 신고",
        description="세금 신고서 작성 및 제출",
        base_k=0.7, base_i=0.0, base_r=0.0,
        automation_level=70,
        energy_cost=2.0,
        external_tool="turbotax",
        enabled_types=[UserType.INDIVIDUAL, UserType.SMALL_TEAM, UserType.SMB]
    ),
    TaskDefinition(
        task_id="L2_FIN_011",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="REPORT",
        name_en="Financial Report",
        name_ko="재무 보고서",
        description="재무제표 자동 생성",
        base_k=0.8, base_i=0.1, base_r=0.0,
        automation_level=80,
        energy_cost=1.5,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_FIN_012",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="REPORT",
        name_en="Cash Flow Analysis",
        name_ko="현금흐름 분석",
        description="현금흐름표 분석 및 예측",
        base_k=0.9, base_i=0.0, base_r=0.0,
        automation_level=85,
        energy_cost=1.2,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_FIN_013",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="AUDIT",
        name_en="Financial Audit",
        name_ko="재무 감사",
        description="내부 재무 감사 수행",
        base_k=0.6, base_i=0.1, base_r=0.0,
        automation_level=50,
        energy_cost=3.0,
        external_tool="internal",
        enabled_types=[UserType.SMB, UserType.ENTERPRISE]
    ),
    TaskDefinition(
        task_id="L2_FIN_014",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="FORECAST",
        name_en="Revenue Forecast",
        name_ko="매출 예측",
        description="AI 기반 매출 예측",
        base_k=0.8, base_i=0.0, base_r=0.02,
        automation_level=85,
        energy_cost=1.5,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_FIN_015",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="PAYROLL",
        name_en="Payroll Processing",
        name_ko="급여 처리",
        description="급여 계산 및 지급",
        base_k=1.0, base_i=0.2, base_r=0.0,
        automation_level=90,
        energy_cost=1.2,
        external_tool="gusto",
        enabled_types=[UserType.SMALL_TEAM, UserType.SMB, UserType.ENTERPRISE]
    ),
    TaskDefinition(
        task_id="L2_FIN_016",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="PAYROLL",
        name_en="Payroll Tax",
        name_ko="급여세 처리",
        description="급여 관련 세금 처리",
        base_k=1.1, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.8,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_FIN_017",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="VENDOR",
        name_en="Vendor Payment",
        name_ko="공급업체 결제",
        description="공급업체 대금 지급",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=85,
        energy_cost=1.0,
        external_tool="bill.com"
    ),
    TaskDefinition(
        task_id="L2_FIN_018",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="VENDOR",
        name_en="Vendor Invoice Matching",
        name_ko="공급업체 송장 매칭",
        description="PO-송장-입고 3way 매칭",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.8,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_FIN_019",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="ASSET",
        name_en="Asset Depreciation",
        name_ko="자산 감가상각",
        description="고정자산 감가상각 계산",
        base_k=1.2, base_i=0.0, base_r=-0.01,
        automation_level=95,
        energy_cost=0.5,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_FIN_020",
        layer=TaskLayer.DOMAIN,
        category="FINANCE",
        subcategory="COMPLIANCE",
        name_en="Financial Compliance",
        name_ko="재무 컴플라이언스",
        description="재무 규정 준수 검사",
        base_k=0.8, base_i=0.0, base_r=0.0,
        automation_level=75,
        energy_cost=1.5,
        external_tool="internal",
        enabled_types=[UserType.SMB, UserType.ENTERPRISE, UserType.NATION]
    ),

    # ─────────────────────────────────────────────────────────────────────────
    # HR 도메인 (HR) - 20개
    # ─────────────────────────────────────────────────────────────────────────
    TaskDefinition(
        task_id="L2_HR_001",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="RECRUIT",
        name_en="Job Posting",
        name_ko="채용 공고",
        description="채용 공고 생성 및 게시",
        base_k=0.8, base_i=0.2, base_r=0.0,
        automation_level=80,
        energy_cost=1.0,
        external_tool="lever"
    ),
    TaskDefinition(
        task_id="L2_HR_002",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="RECRUIT",
        name_en="Resume Screening",
        name_ko="이력서 스크리닝",
        description="AI 기반 이력서 자동 스크리닝",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.8,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_HR_003",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="RECRUIT",
        name_en="Interview Scheduling",
        name_ko="면접 일정 조율",
        description="면접 일정 자동 조율",
        base_k=0.9, base_i=0.3, base_r=0.0,
        automation_level=85,
        energy_cost=0.6,
        external_tool="calendly"
    ),
    TaskDefinition(
        task_id="L2_HR_004",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="ONBOARD",
        name_en="Onboarding Checklist",
        name_ko="온보딩 체크리스트",
        description="신규 입사자 온보딩 프로세스. 개인 타입: 자기계발 통합.",
        base_k=0.8, base_i=0.4, base_r=0.01,
        automation_level=75,
        energy_cost=1.5,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_HR_005",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="ONBOARD",
        name_en="Equipment Provisioning",
        name_ko="장비 지급",
        description="신규 입사자 장비 준비 및 지급",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=80,
        energy_cost=1.0,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_HR_006",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="ONBOARD",
        name_en="Access Provisioning",
        name_ko="접근 권한 설정",
        description="시스템 접근 권한 자동 설정",
        base_k=1.1, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.5,
        external_tool="okta"
    ),
    TaskDefinition(
        task_id="L2_HR_007",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="PERFORMANCE",
        name_en="Performance Review",
        name_ko="성과 평가",
        description="정기 성과 평가 프로세스",
        base_k=0.6, base_i=0.3, base_r=0.0,
        automation_level=50,
        energy_cost=2.5,
        external_tool="lattice"
    ),
    TaskDefinition(
        task_id="L2_HR_008",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="PERFORMANCE",
        name_en="Goal Setting",
        name_ko="목표 설정",
        description="OKR/KPI 목표 설정",
        base_k=0.7, base_i=0.2, base_r=0.0,
        automation_level=60,
        energy_cost=1.5,
        external_tool="lattice"
    ),
    TaskDefinition(
        task_id="L2_HR_009",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="LEARNING",
        name_en="Training Assignment",
        name_ko="교육 배정",
        description="필수 교육 자동 배정",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_HR_010",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="LEARNING",
        name_en="Learning Progress",
        name_ko="학습 진도 추적",
        description="교육 이수 현황 모니터링",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.5,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_HR_011",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="LEAVE",
        name_en="Leave Request",
        name_ko="휴가 신청",
        description="휴가 신청 및 승인 프로세스",
        base_k=1.0, base_i=0.2, base_r=0.0,
        automation_level=90,
        energy_cost=0.4,
        external_tool="bamboohr"
    ),
    TaskDefinition(
        task_id="L2_HR_012",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="LEAVE",
        name_en="Leave Balance",
        name_ko="휴가 잔여일 관리",
        description="휴가 잔여일 자동 계산",
        base_k=1.2, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.3,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_HR_013",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="ATTENDANCE",
        name_en="Time Tracking",
        name_ko="근태 관리",
        description="출퇴근 시간 추적",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.3,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_HR_014",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="ATTENDANCE",
        name_en="Overtime Calculation",
        name_ko="초과근무 계산",
        description="초과근무 시간 자동 계산",
        base_k=1.1, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.4,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_HR_015",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="OFFBOARD",
        name_en="Offboarding Checklist",
        name_ko="퇴사 체크리스트",
        description="퇴사자 프로세스 관리",
        base_k=0.8, base_i=0.1, base_r=-0.02,
        automation_level=80,
        energy_cost=1.0,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_HR_016",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="OFFBOARD",
        name_en="Access Revocation",
        name_ko="접근 권한 회수",
        description="퇴사자 시스템 접근 차단",
        base_k=1.2, base_i=0.0, base_r=0.0,
        automation_level=100,
        energy_cost=0.3,
        external_tool="okta"
    ),
    TaskDefinition(
        task_id="L2_HR_017",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="BENEFITS",
        name_en="Benefits Enrollment",
        name_ko="복리후생 등록",
        description="복리후생 프로그램 가입",
        base_k=0.8, base_i=0.1, base_r=0.0,
        automation_level=75,
        energy_cost=1.0,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_HR_018",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="SURVEY",
        name_en="Employee Survey",
        name_ko="직원 설문",
        description="직원 만족도 설문 조사",
        base_k=0.7, base_i=0.3, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="surveymonkey"
    ),
    TaskDefinition(
        task_id="L2_HR_019",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="ANALYTICS",
        name_en="HR Analytics",
        name_ko="HR 분석",
        description="인력 현황 분석 및 리포팅",
        base_k=0.9, base_i=0.0, base_r=0.0,
        automation_level=80,
        energy_cost=1.2,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_HR_020",
        layer=TaskLayer.DOMAIN,
        category="HR",
        subcategory="COMPLIANCE",
        name_en="HR Compliance",
        name_ko="HR 컴플라이언스",
        description="노동법 준수 검사",
        base_k=0.8, base_i=0.0, base_r=0.0,
        automation_level=70,
        energy_cost=1.5,
        external_tool="internal"
    ),

    # ─────────────────────────────────────────────────────────────────────────
    # 영업 도메인 (SALES) - 15개
    # ─────────────────────────────────────────────────────────────────────────
    TaskDefinition(
        task_id="L2_SALES_001",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="LEAD",
        name_en="Lead Capture",
        name_ko="리드 수집",
        description="잠재 고객 리드 수집. 개인 타입: 네트워킹 스코어 반영.",
        base_k=0.9, base_i=0.2, base_r=0.01,
        automation_level=90,
        energy_cost=0.6,
        external_tool="hubspot"
    ),
    TaskDefinition(
        task_id="L2_SALES_002",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="LEAD",
        name_en="Lead Scoring",
        name_ko="리드 스코어링",
        description="AI 기반 리드 점수 산정. 글로벌 타입: 시장 I 상수 반영.",
        base_k=1.0, base_i=0.1, base_r=0.0,
        automation_level=95,
        energy_cost=0.5,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_SALES_003",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="LEAD",
        name_en="Lead Nurturing",
        name_ko="리드 육성",
        description="리드 육성 캠페인 자동화",
        base_k=0.8, base_i=0.3, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="hubspot"
    ),
    TaskDefinition(
        task_id="L2_SALES_004",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="OPPORTUNITY",
        name_en="Opportunity Creation",
        name_ko="기회 생성",
        description="영업 기회 생성 및 관리",
        base_k=0.8, base_i=0.2, base_r=0.0,
        automation_level=75,
        energy_cost=1.0,
        external_tool="salesforce"
    ),
    TaskDefinition(
        task_id="L2_SALES_005",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="OPPORTUNITY",
        name_en="Pipeline Management",
        name_ko="파이프라인 관리",
        description="영업 파이프라인 추적",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=80,
        energy_cost=0.8,
        external_tool="salesforce"
    ),
    TaskDefinition(
        task_id="L2_SALES_006",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="QUOTE",
        name_en="Quote Generation",
        name_ko="견적 생성",
        description="견적서 자동 생성",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.6,
        external_tool="pandadoc"
    ),
    TaskDefinition(
        task_id="L2_SALES_007",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="CONTRACT",
        name_en="Contract Generation",
        name_ko="계약서 생성",
        description="계약서 자동 생성",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="docusign"
    ),
    TaskDefinition(
        task_id="L2_SALES_008",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="CONTRACT",
        name_en="E-Signature",
        name_ko="전자서명",
        description="전자서명 요청 및 추적",
        base_k=1.1, base_i=0.2, base_r=0.0,
        automation_level=95,
        energy_cost=0.4,
        external_tool="docusign"
    ),
    TaskDefinition(
        task_id="L2_SALES_009",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="FORECAST",
        name_en="Sales Forecast",
        name_ko="영업 예측",
        description="영업 실적 예측",
        base_k=0.8, base_i=0.0, base_r=0.0,
        automation_level=85,
        energy_cost=1.0,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_SALES_010",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="COMMISSION",
        name_en="Commission Calculation",
        name_ko="커미션 계산",
        description="영업 수당 자동 계산",
        base_k=1.1, base_i=0.1, base_r=0.0,
        automation_level=95,
        energy_cost=0.5,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_SALES_011",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="TERRITORY",
        name_en="Territory Assignment",
        name_ko="영역 배정",
        description="영업 담당 구역 배정",
        base_k=0.8, base_i=0.2, base_r=0.0,
        automation_level=70,
        energy_cost=1.0,
        external_tool="internal",
        enabled_types=[UserType.SMB, UserType.ENTERPRISE]
    ),
    TaskDefinition(
        task_id="L2_SALES_012",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="MEETING",
        name_en="Meeting Scheduling",
        name_ko="미팅 일정 조율",
        description="영업 미팅 자동 일정 조율",
        base_k=0.9, base_i=0.3, base_r=0.0,
        automation_level=90,
        energy_cost=0.5,
        external_tool="calendly"
    ),
    TaskDefinition(
        task_id="L2_SALES_013",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="REPORT",
        name_en="Sales Report",
        name_ko="영업 보고서",
        description="영업 실적 보고서 생성",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_SALES_014",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="CRM",
        name_en="CRM Data Update",
        name_ko="CRM 데이터 업데이트",
        description="CRM 고객 데이터 동기화",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.4,
        external_tool="salesforce"
    ),
    TaskDefinition(
        task_id="L2_SALES_015",
        layer=TaskLayer.DOMAIN,
        category="SALES",
        subcategory="UPSELL",
        name_en="Upsell Recommendation",
        name_ko="업셀 추천",
        description="AI 기반 업셀/크로스셀 추천",
        base_k=0.9, base_i=0.2, base_r=0.01,
        automation_level=90,
        energy_cost=0.6,
        external_tool="databricks"
    ),

    # ─────────────────────────────────────────────────────────────────────────
    # 마케팅 도메인 (MARKETING) - 15개
    # ─────────────────────────────────────────────────────────────────────────
    TaskDefinition(
        task_id="L2_MKT_001",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="CAMPAIGN",
        name_en="Campaign Creation",
        name_ko="캠페인 생성",
        description="마케팅 캠페인 생성",
        base_k=0.8, base_i=0.2, base_r=0.0,
        automation_level=75,
        energy_cost=1.5,
        external_tool="hubspot"
    ),
    TaskDefinition(
        task_id="L2_MKT_002",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="CAMPAIGN",
        name_en="Campaign Launch",
        name_ko="캠페인 실행",
        description="마케팅 캠페인 실행 및 모니터링",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=85,
        energy_cost=1.0,
        external_tool="hubspot"
    ),
    TaskDefinition(
        task_id="L2_MKT_003",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="EMAIL",
        name_en="Email Campaign",
        name_ko="이메일 캠페인",
        description="이메일 마케팅 자동화",
        base_k=0.8, base_i=0.1, base_r=0.0,
        automation_level=90,
        energy_cost=0.6,
        external_tool="mailchimp"
    ),
    TaskDefinition(
        task_id="L2_MKT_004",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="SOCIAL",
        name_en="Social Media Posting",
        name_ko="소셜미디어 포스팅",
        description="소셜미디어 게시물 예약 및 발행",
        base_k=0.7, base_i=0.3, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="buffer"
    ),
    TaskDefinition(
        task_id="L2_MKT_005",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="SOCIAL",
        name_en="Social Listening",
        name_ko="소셜 리스닝",
        description="소셜미디어 언급 모니터링",
        base_k=0.9, base_i=0.2, base_r=0.0,
        automation_level=90,
        energy_cost=0.5,
        external_tool="brandwatch"
    ),
    TaskDefinition(
        task_id="L2_MKT_006",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="CONTENT",
        name_en="Content Creation",
        name_ko="콘텐츠 제작",
        description="마케팅 콘텐츠 제작",
        base_k=0.6, base_i=0.2, base_r=0.0,
        automation_level=60,
        energy_cost=2.0,
        external_tool="canva"
    ),
    TaskDefinition(
        task_id="L2_MKT_007",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="CONTENT",
        name_en="Content Publishing",
        name_ko="콘텐츠 발행",
        description="콘텐츠 발행 및 배포",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=90,
        energy_cost=0.5,
        external_tool="wordpress"
    ),
    TaskDefinition(
        task_id="L2_MKT_008",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="SEO",
        name_en="SEO Optimization",
        name_ko="SEO 최적화",
        description="검색엔진 최적화",
        base_k=0.8, base_i=0.0, base_r=0.01,
        automation_level=75,
        energy_cost=1.2,
        external_tool="semrush"
    ),
    TaskDefinition(
        task_id="L2_MKT_009",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="ADS",
        name_en="Ad Campaign Management",
        name_ko="광고 캠페인 관리",
        description="유료 광고 캠페인 관리",
        base_k=0.7, base_i=0.0, base_r=0.0,
        automation_level=80,
        energy_cost=1.5,
        external_tool="google_ads"
    ),
    TaskDefinition(
        task_id="L2_MKT_010",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="ADS",
        name_en="Ad Performance Analysis",
        name_ko="광고 성과 분석",
        description="광고 ROI 분석",
        base_k=0.9, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.8,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_MKT_011",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="ANALYTICS",
        name_en="Marketing Analytics",
        name_ko="마케팅 분석",
        description="마케팅 성과 분석 및 리포팅",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=85,
        energy_cost=1.0,
        external_tool="google_analytics"
    ),
    TaskDefinition(
        task_id="L2_MKT_012",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="EVENT",
        name_en="Event Management",
        name_ko="이벤트 관리",
        description="마케팅 이벤트 기획 및 운영",
        base_k=0.7, base_i=0.4, base_r=0.0,
        automation_level=65,
        energy_cost=2.0,
        external_tool="eventbrite"
    ),
    TaskDefinition(
        task_id="L2_MKT_013",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="WEBINAR",
        name_en="Webinar Management",
        name_ko="웨비나 관리",
        description="웨비나 일정 및 등록 관리",
        base_k=0.8, base_i=0.3, base_r=0.0,
        automation_level=80,
        energy_cost=1.2,
        external_tool="zoom"
    ),
    TaskDefinition(
        task_id="L2_MKT_014",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="ATTRIBUTION",
        name_en="Attribution Modeling",
        name_ko="기여도 분석",
        description="마케팅 채널 기여도 분석",
        base_k=0.9, base_i=0.0, base_r=0.0,
        automation_level=85,
        energy_cost=1.0,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_MKT_015",
        layer=TaskLayer.DOMAIN,
        category="MARKETING",
        subcategory="BRAND",
        name_en="Brand Monitoring",
        name_ko="브랜드 모니터링",
        description="브랜드 인지도 및 평판 모니터링",
        base_k=0.8, base_i=0.2, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="brandwatch"
    ),

    # ─────────────────────────────────────────────────────────────────────────
    # IT 도메인 (IT) - 15개
    # ─────────────────────────────────────────────────────────────────────────
    TaskDefinition(
        task_id="L2_IT_001",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="TICKET",
        name_en="Ticket Creation",
        name_ko="티켓 생성",
        description="IT 지원 티켓 생성",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=90,
        energy_cost=0.4,
        external_tool="jira"
    ),
    TaskDefinition(
        task_id="L2_IT_002",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="TICKET",
        name_en="Ticket Routing",
        name_ko="티켓 라우팅",
        description="티켓 자동 분류 및 배정",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.3,
        external_tool="jira"
    ),
    TaskDefinition(
        task_id="L2_IT_003",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="DEPLOY",
        name_en="Code Deployment",
        name_ko="코드 배포",
        description="CI/CD 파이프라인 실행",
        base_k=1.1, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.8,
        external_tool="github_actions"
    ),
    TaskDefinition(
        task_id="L2_IT_004",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="REVIEW",
        name_en="Code Review",
        name_ko="코드 리뷰",
        description="코드 리뷰 프로세스. 개인 타입: 학습 루틴. 중소기업 타입: 팀 I 최적화.",
        base_k=0.8, base_i=0.4, base_r=0.0,
        automation_level=60,
        energy_cost=1.5,
        external_tool="github"
    ),
    TaskDefinition(
        task_id="L2_IT_005",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="MONITOR",
        name_en="System Monitoring",
        name_ko="시스템 모니터링",
        description="인프라 모니터링 및 알림",
        base_k=1.2, base_i=0.0, base_r=0.0,
        automation_level=100,
        energy_cost=0.3,
        external_tool="datadog"
    ),
    TaskDefinition(
        task_id="L2_IT_006",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="INCIDENT",
        name_en="Incident Response",
        name_ko="장애 대응",
        description="장애 감지 및 대응 프로세스",
        base_k=1.0, base_i=0.2, base_r=0.0,
        automation_level=85,
        energy_cost=1.0,
        external_tool="pagerduty"
    ),
    TaskDefinition(
        task_id="L2_IT_007",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="BACKUP",
        name_en="System Backup",
        name_ko="시스템 백업",
        description="자동 시스템 백업",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=100,
        energy_cost=0.5,
        external_tool="aws"
    ),
    TaskDefinition(
        task_id="L2_IT_008",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="SECURITY",
        name_en="Vulnerability Scan",
        name_ko="취약점 스캔",
        description="보안 취약점 자동 스캔",
        base_k=1.1, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.6,
        external_tool="snyk"
    ),
    TaskDefinition(
        task_id="L2_IT_009",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="SECURITY",
        name_en="Access Review",
        name_ko="접근 권한 검토",
        description="정기 접근 권한 검토",
        base_k=0.8, base_i=0.1, base_r=0.0,
        automation_level=75,
        energy_cost=1.0,
        external_tool="okta"
    ),
    TaskDefinition(
        task_id="L2_IT_010",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="INFRA",
        name_en="Infrastructure Provisioning",
        name_ko="인프라 프로비저닝",
        description="클라우드 리소스 자동 생성",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.8,
        external_tool="terraform"
    ),
    TaskDefinition(
        task_id="L2_IT_011",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="INFRA",
        name_en="Cost Optimization",
        name_ko="비용 최적화",
        description="클라우드 비용 최적화 분석",
        base_k=0.9, base_i=0.0, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="aws"
    ),
    TaskDefinition(
        task_id="L2_IT_012",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="DATABASE",
        name_en="Database Maintenance",
        name_ko="데이터베이스 유지보수",
        description="DB 인덱스/통계 최적화",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.6,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_IT_013",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="API",
        name_en="API Gateway Management",
        name_ko="API 게이트웨이 관리",
        description="API 라우팅 및 제한 관리",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.5,
        external_tool="kong"
    ),
    TaskDefinition(
        task_id="L2_IT_014",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="DOCUMENTATION",
        name_en="Tech Documentation",
        name_ko="기술 문서화",
        description="기술 문서 자동 생성",
        base_k=0.7, base_i=0.2, base_r=0.0,
        automation_level=70,
        energy_cost=1.2,
        external_tool="confluence"
    ),
    TaskDefinition(
        task_id="L2_IT_015",
        layer=TaskLayer.DOMAIN,
        category="IT",
        subcategory="CHANGE",
        name_en="Change Management",
        name_ko="변경 관리",
        description="IT 변경 요청 승인 프로세스",
        base_k=0.8, base_i=0.2, base_r=0.0,
        automation_level=70,
        energy_cost=1.0,
        external_tool="servicenow",
        enabled_types=[UserType.SMB, UserType.ENTERPRISE]
    ),

    # ─────────────────────────────────────────────────────────────────────────
    # 운영 도메인 (OPERATIONS) - 15개
    # ─────────────────────────────────────────────────────────────────────────
    TaskDefinition(
        task_id="L2_OPS_001",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="INVENTORY",
        name_en="Inventory Check",
        name_ko="재고 확인",
        description="재고 현황 모니터링",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.4,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_OPS_002",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="INVENTORY",
        name_en="Reorder Alert",
        name_ko="재주문 알림",
        description="재고 부족 시 자동 알림",
        base_k=1.1, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.3,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_OPS_003",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="ORDER",
        name_en="Order Processing",
        name_ko="주문 처리",
        description="주문 접수 및 처리",
        base_k=1.0, base_i=0.1, base_r=0.0,
        automation_level=90,
        energy_cost=0.6,
        external_tool="shopify"
    ),
    TaskDefinition(
        task_id="L2_OPS_004",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="ORDER",
        name_en="Order Fulfillment",
        name_ko="주문 이행",
        description="주문 출고 및 배송",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="shipstation"
    ),
    TaskDefinition(
        task_id="L2_OPS_005",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="SHIPPING",
        name_en="Shipping Label",
        name_ko="배송 라벨 생성",
        description="배송 라벨 자동 생성",
        base_k=1.1, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.3,
        external_tool="shipstation"
    ),
    TaskDefinition(
        task_id="L2_OPS_006",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="SHIPPING",
        name_en="Shipment Tracking",
        name_ko="배송 추적",
        description="실시간 배송 추적",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.3,
        external_tool="aftership"
    ),
    TaskDefinition(
        task_id="L2_OPS_007",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="RETURN",
        name_en="Return Processing",
        name_ko="반품 처리",
        description="반품 접수 및 처리",
        base_k=0.8, base_i=0.1, base_r=0.0,
        automation_level=80,
        energy_cost=1.0,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_OPS_008",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="VENDOR",
        name_en="Vendor Communication",
        name_ko="공급업체 커뮤니케이션",
        description="공급업체 소통 자동화",
        base_k=0.8, base_i=0.3, base_r=0.0,
        automation_level=75,
        energy_cost=0.8,
        external_tool="slack"
    ),
    TaskDefinition(
        task_id="L2_OPS_009",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="QUALITY",
        name_en="Quality Check",
        name_ko="품질 검사",
        description="제품 품질 검사 프로세스",
        base_k=0.9, base_i=0.0, base_r=0.0,
        automation_level=70,
        energy_cost=1.2,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_OPS_010",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="SCHEDULING",
        name_en="Production Scheduling",
        name_ko="생산 일정 관리",
        description="생산 일정 계획 및 조정",
        base_k=0.8, base_i=0.2, base_r=0.0,
        automation_level=75,
        energy_cost=1.5,
        external_tool="internal",
        enabled_types=[UserType.SMB, UserType.ENTERPRISE]
    ),
    TaskDefinition(
        task_id="L2_OPS_011",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="MAINTENANCE",
        name_en="Equipment Maintenance",
        name_ko="설비 유지보수",
        description="예방 정비 일정 관리",
        base_k=0.9, base_i=0.0, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_OPS_012",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="PROCUREMENT",
        name_en="Purchase Order",
        name_ko="구매 발주",
        description="구매 발주서 생성",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=85,
        energy_cost=0.6,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_OPS_013",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="PROCUREMENT",
        name_en="Vendor Evaluation",
        name_ko="공급업체 평가",
        description="공급업체 성과 평가",
        base_k=0.8, base_i=0.2, base_r=0.0,
        automation_level=70,
        energy_cost=1.0,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_OPS_014",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="REPORT",
        name_en="Operations Report",
        name_ko="운영 보고서",
        description="일일 운영 현황 리포트",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=90,
        energy_cost=0.6,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_OPS_015",
        layer=TaskLayer.DOMAIN,
        category="OPERATIONS",
        subcategory="OPTIMIZATION",
        name_en="Process Optimization",
        name_ko="프로세스 최적화",
        description="운영 프로세스 분석 및 최적화",
        base_k=0.7, base_i=0.0, base_r=0.02,
        automation_level=75,
        energy_cost=1.5,
        external_tool="databricks"
    ),

    # ─────────────────────────────────────────────────────────────────────────
    # 법무 도메인 (LEGAL) - 10개
    # ─────────────────────────────────────────────────────────────────────────
    TaskDefinition(
        task_id="L2_LEGAL_001",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="CONTRACT",
        name_en="Contract Review",
        name_ko="계약서 검토",
        description="계약서 조항 자동 검토",
        base_k=0.8, base_i=0.0, base_r=0.0,
        automation_level=70,
        energy_cost=1.5,
        external_tool="internal",
        enabled_types=[UserType.SMB, UserType.ENTERPRISE]
    ),
    TaskDefinition(
        task_id="L2_LEGAL_002",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="CONTRACT",
        name_en="Contract Template",
        name_ko="계약서 템플릿",
        description="표준 계약서 템플릿 관리",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=85,
        energy_cost=0.6,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_LEGAL_003",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="CONTRACT",
        name_en="Contract Expiry Alert",
        name_ko="계약 만료 알림",
        description="계약 만료 자동 알림",
        base_k=1.1, base_i=0.1, base_r=0.0,
        automation_level=95,
        energy_cost=0.3,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_LEGAL_004",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="COMPLIANCE",
        name_en="Compliance Check",
        name_ko="컴플라이언스 검사",
        description="규정 준수 자동 검사",
        base_k=0.9, base_i=0.0, base_r=0.0,
        automation_level=80,
        energy_cost=1.0,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_LEGAL_005",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="PRIVACY",
        name_en="GDPR Processing",
        name_ko="GDPR 처리",
        description="GDPR 요청 처리 (삭제, 조회)",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_LEGAL_006",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="PRIVACY",
        name_en="Privacy Consent",
        name_ko="개인정보 동의",
        description="개인정보 동의 수집 및 관리",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=90,
        energy_cost=0.4,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_LEGAL_007",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="IP",
        name_en="Trademark Monitoring",
        name_ko="상표 모니터링",
        description="상표권 침해 모니터링",
        base_k=0.8, base_i=0.0, base_r=0.0,
        automation_level=80,
        energy_cost=0.8,
        external_tool="internal",
        enabled_types=[UserType.SMB, UserType.ENTERPRISE]
    ),
    TaskDefinition(
        task_id="L2_LEGAL_008",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="POLICY",
        name_en="Policy Update",
        name_ko="정책 업데이트",
        description="법적 정책 문서 업데이트",
        base_k=0.7, base_i=0.1, base_r=0.0,
        automation_level=60,
        energy_cost=1.5,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_LEGAL_009",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="DISPUTE",
        name_en="Dispute Tracking",
        name_ko="분쟁 추적",
        description="법적 분쟁 현황 추적",
        base_k=0.7, base_i=0.1, base_r=0.0,
        automation_level=70,
        energy_cost=1.2,
        external_tool="internal",
        enabled_types=[UserType.SMB, UserType.ENTERPRISE]
    ),
    TaskDefinition(
        task_id="L2_LEGAL_010",
        layer=TaskLayer.DOMAIN,
        category="LEGAL",
        subcategory="ARCHIVE",
        name_en="Legal Document Archive",
        name_ko="법률 문서 보관",
        description="법률 문서 보관 및 관리",
        base_k=0.9, base_i=0.0, base_r=-0.01,
        automation_level=90,
        energy_cost=0.5,
        external_tool="internal"
    ),

    # ─────────────────────────────────────────────────────────────────────────
    # 고객지원 도메인 (SUPPORT) - 10개
    # ─────────────────────────────────────────────────────────────────────────
    TaskDefinition(
        task_id="L2_SUPPORT_001",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="TICKET",
        name_en="Support Ticket",
        name_ko="지원 티켓 생성",
        description="고객 문의 티켓 생성",
        base_k=0.9, base_i=0.1, base_r=0.0,
        automation_level=90,
        energy_cost=0.4,
        external_tool="zendesk"
    ),
    TaskDefinition(
        task_id="L2_SUPPORT_002",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="TICKET",
        name_en="Ticket Classification",
        name_ko="티켓 분류",
        description="AI 기반 티켓 자동 분류",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=95,
        energy_cost=0.3,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_SUPPORT_003",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="RESPONSE",
        name_en="Auto Response",
        name_ko="자동 응답",
        description="자주 묻는 질문 자동 응답",
        base_k=1.1, base_i=0.1, base_r=0.0,
        automation_level=90,
        energy_cost=0.3,
        external_tool="intercom"
    ),
    TaskDefinition(
        task_id="L2_SUPPORT_004",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="RESPONSE",
        name_en="Response Template",
        name_ko="응답 템플릿",
        description="응답 템플릿 관리",
        base_k=1.0, base_i=0.0, base_r=0.0,
        automation_level=85,
        energy_cost=0.4,
        external_tool="internal"
    ),
    TaskDefinition(
        task_id="L2_SUPPORT_005",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="CHAT",
        name_en="Live Chat",
        name_ko="실시간 채팅",
        description="실시간 고객 채팅 지원",
        base_k=0.8, base_i=0.4, base_r=0.0,
        automation_level=70,
        energy_cost=1.0,
        external_tool="intercom"
    ),
    TaskDefinition(
        task_id="L2_SUPPORT_006",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="CHATBOT",
        name_en="Chatbot",
        name_ko="챗봇 응대",
        description="AI 챗봇 자동 응대",
        base_k=1.0, base_i=0.2, base_r=0.01,
        automation_level=95,
        energy_cost=0.4,
        external_tool="intercom"
    ),
    TaskDefinition(
        task_id="L2_SUPPORT_007",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="ESCALATION",
        name_en="Ticket Escalation",
        name_ko="티켓 에스컬레이션",
        description="미해결 티켓 자동 에스컬레이션",
        base_k=0.9, base_i=0.2, base_r=0.0,
        automation_level=90,
        energy_cost=0.4,
        external_tool="zendesk"
    ),
    TaskDefinition(
        task_id="L2_SUPPORT_008",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="FEEDBACK",
        name_en="Customer Feedback",
        name_ko="고객 피드백 수집",
        description="고객 만족도 설문 발송",
        base_k=0.9, base_i=0.2, base_r=0.0,
        automation_level=90,
        energy_cost=0.4,
        external_tool="surveymonkey"
    ),
    TaskDefinition(
        task_id="L2_SUPPORT_009",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="ANALYTICS",
        name_en="Support Analytics",
        name_ko="지원 분석",
        description="고객 지원 성과 분석",
        base_k=0.9, base_i=0.0, base_r=0.0,
        automation_level=85,
        energy_cost=0.8,
        external_tool="databricks"
    ),
    TaskDefinition(
        task_id="L2_SUPPORT_010",
        layer=TaskLayer.DOMAIN,
        category="SUPPORT",
        subcategory="KB",
        name_en="Knowledge Base Update",
        name_ko="지식베이스 업데이트",
        description="FAQ 및 도움말 문서 업데이트",
        base_k=0.8, base_i=0.1, base_r=0.0,
        automation_level=70,
        energy_cost=1.0,
        external_tool="confluence"
    ),
]


# ═══════════════════════════════════════════════════════════════════════════════
# 카테고리 요약
# ═══════════════════════════════════════════════════════════════════════════════

DOMAIN_CATEGORY_SUMMARY = {
    "FINANCE": {"count": 20, "description": "재무 도메인"},
    "HR": {"count": 20, "description": "HR 도메인"},
    "SALES": {"count": 15, "description": "영업 도메인"},
    "MARKETING": {"count": 15, "description": "마케팅 도메인"},
    "IT": {"count": 15, "description": "IT 도메인"},
    "OPERATIONS": {"count": 15, "description": "운영 도메인"},
    "LEGAL": {"count": 10, "description": "법무 도메인"},
    "SUPPORT": {"count": 10, "description": "고객지원 도메인"},
}


def get_domain_tasks_by_category(category: str) -> list[TaskDefinition]:
    """도메인 카테고리별 업무 조회"""
    return [t for t in DOMAIN_LOGIC_120 if t.category == category]
