"""
Tests for AUTUS Logger
Generated by: AUTUS testgen_pack
"""

import pytest
from pathlib import Path
import tempfile
from protocols.logging.logger import AUTUSLogger

class TestAUTUSLogger:
    """Test suite for AUTUSLogger"""
    
    def test_initialization(self):
        """Test logger initializes"""
        logger = AUTUSLogger("test")
        assert logger.logger.name == "test"
    
    def test_logging_methods(self):
        """Test all logging methods work"""
        logger = AUTUSLogger("test")
        
        # Should not raise
        logger.debug("debug")
        logger.info("info")
        logger.warning("warning")
        logger.error("error")
        logger.critical("critical")
    
    def test_file_logging(self):
        """Test logging to file"""
        with tempfile.TemporaryDirectory() as tmpdir:
            log_file = Path(tmpdir) / "test.log"
            logger = AUTUSLogger("test", log_file=log_file)
            
            logger.info("test message")
            
            assert log_file.exists()
            content = log_file.read_text()
            assert "test message" in content

if __name__ == "__main__":
    print("Running tests...")
    pytest.main([__file__, "-v"])
