// ═══════════════════════════════════════════════════════════════════════════════
// AUTUS v2.0 - 570개 업무 DNA 데이터베이스
// 글로벌 표준 업무 프로세스 전수 조사
// ═══════════════════════════════════════════════════════════════════════════════

import { TaskDNA, TaskDomain, TaskPhysics, R1Insight } from './taskDNA';
import { ScaleLevel } from '../physics';

// ═══════════════════════════════════════════════════════════════════════════════
// 업무 생성 헬퍼
// ═══════════════════════════════════════════════════════════════════════════════

function createTask(
  id: string,
  name: string,
  nameEn: string,
  domain: TaskDomain,
  subDomain: string,
  altitude: ScaleLevel,
  physics: Partial<TaskPhysics>,
  insightCore: string,
  tags: string[] = []
): TaskDNA {
  const fullPhysics: TaskPhysics = {
    mass: physics.mass ?? 5,
    psi: physics.psi ?? 5,
    interference: physics.interference ?? 5,
    omega: physics.omega ?? 0.5,
    growth: physics.growth ?? 0,
    criticalTime: physics.criticalTime ?? 48,
    energyConsumption: physics.energyConsumption ?? 5,
  };

  return {
    id,
    name,
    nameEn,
    domain,
    subDomain,
    altitude,
    physics: fullPhysics,
    insight: {
      core: insightCore,
      risks: [],
      opportunities: [],
      causalChain: [],
      optimalConditions: [],
      failureImpact: '',
      confidence: 0.85,
    },
    interference: {
      amplifies: [],
      dampens: [],
      dependsOn: [],
      dependedBy: [],
      exclusive: [],
    },
    periodicity: { type: 'event_driven' },
    automation: {
      potential: 0.5,
      current: 0.2,
      automatable: [],
      humanRequired: [],
      recommendedTools: [],
    },
    metadata: {
      avgDuration: '4h',
      kpis: [],
      tags,
    },
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// 1. 법무 (LEGAL) - 48개
// ═══════════════════════════════════════════════════════════════════════════════

const LEGAL_TASKS: TaskDNA[] = [
  createTask('L-001', '계약서 검토', 'Contract Review', 'LEGAL', '계약', 'K4', 
    { mass: 7.5, psi: 7.0, interference: 5.5, omega: 0.4 },
    '계약 조항의 누락은 미래 분쟁의 씨앗. 초기 검토가 10배의 비용을 절감함.', ['계약', '검토']),
  createTask('L-002', '핵심 기술 특허 출원', 'Core Technology Patent Filing', 'LEGAL', '지식재산', 'K6',
    { mass: 9.8, psi: 9.5, interference: 7.2, omega: 0.3, criticalTime: 720 },
    '출원 시점의 실수는 향후 20년의 자본 궤도를 파괴함. 중력 잠금 필수.', ['특허', '핵심기술']),
  createTask('L-003', '상표권 등록', 'Trademark Registration', 'LEGAL', '지식재산', 'K5',
    { mass: 7.0, psi: 8.0, interference: 4.0, omega: 0.3 },
    '브랜드 자산의 법적 보호. 선출원주의 국가에서는 속도가 생명.', ['상표', '브랜드']),
  createTask('L-004', '소송 대응', 'Litigation Response', 'LEGAL', '소송', 'K7',
    { mass: 9.0, psi: 8.5, interference: 6.0, omega: 0.7 },
    '법적 분쟁은 조직의 에너지를 급격히 소모. 예방이 치료보다 100배 저렴.', ['소송', '분쟁']),
  createTask('L-005', '법률 자문 요청', 'Legal Consultation Request', 'LEGAL', '자문', 'K3',
    { mass: 4.5, psi: 3.0, interference: 6.5, omega: 0.3 },
    '불확실성 해소의 첫 단계. 조기 자문이 리스크를 차단.', ['자문', '상담']),
  createTask('L-006', 'NDA 체결', 'NDA Execution', 'LEGAL', '계약', 'K3',
    { mass: 5.0, psi: 6.0, interference: 7.0, omega: 0.2 },
    '정보 보호의 법적 울타리. 누락 시 핵심 자산 유출.', ['NDA', '기밀']),
  createTask('L-007', '이사회 결의록 작성', 'Board Resolution Drafting', 'LEGAL', '거버넌스', 'K6',
    { mass: 7.5, psi: 8.5, interference: 4.0, omega: 0.2 },
    '법적 구속력을 가진 의사결정 기록. 형식 오류가 결의 무효를 초래.', ['이사회', '결의']),
  createTask('L-008', '규제 대응 검토', 'Regulatory Response Review', 'LEGAL', '규제', 'K5',
    { mass: 8.0, psi: 7.5, interference: 5.5, omega: 0.5 },
    '규제 변화는 사업 모델을 순식간에 무력화. 선제적 대응 필수.', ['규제', '컴플라이언스']),
  createTask('L-009', '라이선스 계약', 'License Agreement', 'LEGAL', '계약', 'K5',
    { mass: 7.0, psi: 7.0, interference: 6.0, omega: 0.4 },
    '지식재산권의 상업화 통로. 조건 설정이 수익 구조를 결정.', ['라이선스', '계약']),
  createTask('L-010', '고용 계약 검토', 'Employment Contract Review', 'LEGAL', '노무', 'K4',
    { mass: 6.0, psi: 6.5, interference: 7.5, omega: 0.3 },
    '노동법 준수는 기본. 핵심 인재의 경업금지 조항 설계가 관건.', ['고용', '노무']),
  createTask('L-011', '개인정보 처리방침 수립', 'Privacy Policy Development', 'LEGAL', '개인정보', 'K5',
    { mass: 7.5, psi: 8.0, interference: 6.0, omega: 0.4 },
    'GDPR/개인정보보호법 위반은 매출의 4%까지 과징금. 설계가 방어막.', ['개인정보', 'GDPR']),
  createTask('L-012', 'M&A 법률 실사', 'M&A Legal Due Diligence', 'LEGAL', 'M&A', 'K8',
    { mass: 9.5, psi: 9.0, interference: 5.0, omega: 0.6, criticalTime: 240 },
    '숨겨진 부채와 소송 리스크 발견. 실사 품질이 거래 성패를 좌우.', ['M&A', '실사']),
  createTask('L-013', '투자 계약서 작성', 'Investment Agreement Drafting', 'LEGAL', '투자', 'K7',
    { mass: 9.0, psi: 8.5, interference: 5.5, omega: 0.4 },
    '지분 구조와 의사결정권의 설계도. 한 줄이 수십억의 가치를 결정.', ['투자', '계약']),
  createTask('L-014', '주주간 계약 검토', 'Shareholders Agreement Review', 'LEGAL', '투자', 'K7',
    { mass: 8.5, psi: 8.0, interference: 5.0, omega: 0.3 },
    '창업자와 투자자 간 권리의 경계. 분쟁 예방의 핵심 문서.', ['주주', '계약']),
  createTask('L-015', '지적재산권 침해 대응', 'IP Infringement Response', 'LEGAL', '지식재산', 'K6',
    { mass: 8.5, psi: 8.0, interference: 6.5, omega: 0.6 },
    '기술 자산에 대한 공격. 신속한 대응이 시장 지위를 방어.', ['IP', '침해']),
  createTask('L-016', '정관 개정', 'Articles Amendment', 'LEGAL', '거버넌스', 'K8',
    { mass: 8.0, psi: 9.0, interference: 4.0, omega: 0.2, criticalTime: 168 },
    '회사의 헌법 수정. 주주총회 특별결의 필요. 비가역적.', ['정관', '거버넌스']),
  createTask('L-017', '분쟁 조정/중재', 'Dispute Mediation/Arbitration', 'LEGAL', '소송', 'K6',
    { mass: 7.5, psi: 7.0, interference: 5.0, omega: 0.5 },
    '소송 대비 70% 비용 절감. 관계 유지와 시간 단축의 균형.', ['중재', '분쟁']),
  createTask('L-018', '약관 작성/검토', 'Terms of Service Drafting', 'LEGAL', '계약', 'K4',
    { mass: 6.5, psi: 7.0, interference: 8.0, omega: 0.3 },
    '수만 고객과의 계약. 한 조항이 집단소송을 유발할 수 있음.', ['약관', '서비스']),
  createTask('L-019', '공정거래 검토', 'Fair Trade Review', 'LEGAL', '규제', 'K5',
    { mass: 7.5, psi: 8.0, interference: 6.0, omega: 0.4 },
    '시장지배적 지위 남용, 담합 리스크 점검. 과징금이 기업가치를 훼손.', ['공정거래', '규제']),
  createTask('L-020', '해외 법인 설립', 'Foreign Subsidiary Establishment', 'LEGAL', '해외', 'K6',
    { mass: 8.0, psi: 7.5, interference: 5.0, omega: 0.5, criticalTime: 480 },
    '현지 법제도 이해가 필수. 잘못된 구조는 세금 폭탄.', ['해외', '법인']),
  createTask('L-021', '수출입 규제 검토', 'Export/Import Regulation Review', 'LEGAL', '규제', 'K5',
    { mass: 7.0, psi: 7.5, interference: 5.5, omega: 0.4 },
    '전략물자 수출은 형사처벌 대상. 사전 검토 필수.', ['수출', '규제']),
  createTask('L-022', '환경법 컴플라이언스', 'Environmental Law Compliance', 'LEGAL', '규제', 'K5',
    { mass: 7.5, psi: 8.0, interference: 4.5, omega: 0.4 },
    'ESG 시대의 필수 요건. 환경 위반은 브랜드 가치를 파괴.', ['환경', 'ESG']),
  createTask('L-023', '노동 분쟁 대응', 'Labor Dispute Response', 'LEGAL', '노무', 'K6',
    { mass: 8.0, psi: 7.5, interference: 7.0, omega: 0.6 },
    '조직 문화와 생산성에 직접 영향. 예방적 노사관계가 최선.', ['노동', '분쟁']),
  createTask('L-024', '임원 책임보험 검토', 'D&O Insurance Review', 'LEGAL', '리스크', 'K6',
    { mass: 7.0, psi: 6.5, interference: 4.0, omega: 0.3 },
    '임원의 개인 자산 보호. 보상 범위와 제외 조항 확인 필수.', ['보험', '임원']),
  createTask('L-025', '법인 등기 변경', 'Corporate Registry Change', 'LEGAL', '거버넌스', 'K4',
    { mass: 5.5, psi: 6.0, interference: 5.0, omega: 0.2 },
    '대표이사, 주소, 목적 변경의 법적 효력 발생 시점.', ['등기', '변경']),
  createTask('L-026', '공시 의무 이행', 'Disclosure Obligation Compliance', 'LEGAL', '규제', 'K6',
    { mass: 8.0, psi: 8.5, interference: 5.0, omega: 0.3, criticalTime: 24 },
    '상장사 필수. 지연 공시는 과징금과 주가 급락을 유발.', ['공시', '상장']),
  createTask('L-027', '내부거래 규정 수립', 'Insider Trading Policy', 'LEGAL', '규제', 'K6',
    { mass: 7.5, psi: 8.0, interference: 5.5, omega: 0.3 },
    '임직원 주식거래 통제. 위반 시 형사처벌.', ['내부거래', '규정']),
  createTask('L-028', '보안 사고 법적 대응', 'Security Incident Legal Response', 'LEGAL', '개인정보', 'K7',
    { mass: 9.0, psi: 8.5, interference: 7.0, omega: 0.7, criticalTime: 72 },
    '72시간 내 신고 의무. 대응 속도가 과징금 규모를 결정.', ['보안', '사고']),
  createTask('L-029', '협력사 계약 관리', 'Vendor Contract Management', 'LEGAL', '계약', 'K4',
    { mass: 6.0, psi: 5.5, interference: 7.0, omega: 0.4 },
    '공급망 리스크의 법적 통제. 품질/납기 조항이 핵심.', ['협력사', '계약']),
  createTask('L-030', '프랜차이즈 계약', 'Franchise Agreement', 'LEGAL', '계약', 'K5',
    { mass: 7.5, psi: 7.0, interference: 6.0, omega: 0.4 },
    '브랜드 확장의 법적 구조. 가맹점주 보호 규정 준수 필수.', ['프랜차이즈', '계약']),
  createTask('L-031', '영업비밀 보호 정책', 'Trade Secret Protection Policy', 'LEGAL', '지식재산', 'K5',
    { mass: 7.5, psi: 8.0, interference: 5.5, omega: 0.3 },
    '기술 유출 예방의 첫 단계. 보호조치 미비 시 법적 보호 불가.', ['영업비밀', '보호']),
  createTask('L-032', '법률 리스크 평가', 'Legal Risk Assessment', 'LEGAL', '리스크', 'K5',
    { mass: 7.0, psi: 6.0, interference: 7.0, omega: 0.5 },
    '주기적 점검으로 잠재 리스크 식별. 예방 비용은 치료의 1/10.', ['리스크', '평가']),
  createTask('L-033', '준법 교육 실시', 'Compliance Training', 'LEGAL', '규제', 'K3',
    { mass: 4.5, psi: 4.0, interference: 8.0, omega: 0.3 },
    '임직원 인식 제고. 위반 시 "알고 있었다"는 항변 차단.', ['교육', '컴플라이언스']),
  createTask('L-034', '윤리 경영 가이드라인', 'Ethics Management Guidelines', 'LEGAL', '거버넌스', 'K5',
    { mass: 6.5, psi: 5.5, interference: 6.0, omega: 0.3 },
    'ESG S(사회) 요소의 핵심. 내부고발 채널 필수.', ['윤리', 'ESG']),
  createTask('L-035', '국제 중재 대응', 'International Arbitration Response', 'LEGAL', '소송', 'K8',
    { mass: 9.5, psi: 9.0, interference: 4.5, omega: 0.6, criticalTime: 168 },
    '국경을 넘는 분쟁. 준거법과 중재지 선택이 승패를 좌우.', ['국제', '중재']),
  createTask('L-036', '제품 책임 대응', 'Product Liability Response', 'LEGAL', '소송', 'K7',
    { mass: 9.0, psi: 8.5, interference: 6.0, omega: 0.7 },
    '리콜, 손해배상, 브랜드 훼손의 삼중고. 품질 문서화가 방어막.', ['제품', '책임']),
  createTask('L-037', '반부패 정책 수립', 'Anti-Corruption Policy', 'LEGAL', '규제', 'K6',
    { mass: 8.0, psi: 8.5, interference: 5.5, omega: 0.3 },
    'FCPA/UK Bribery Act 적용 대상. 위반 시 수십억 과징금.', ['반부패', '규제']),
  createTask('L-038', '데이터 국외 이전 검토', 'Cross-Border Data Transfer Review', 'LEGAL', '개인정보', 'K5',
    { mass: 7.5, psi: 7.5, interference: 5.0, omega: 0.4 },
    '클라우드 시대의 필수 검토. EU-적정성 결정 활용.', ['데이터', '국외이전']),
  createTask('L-039', '소프트웨어 라이선스 감사', 'Software License Audit', 'LEGAL', '지식재산', 'K4',
    { mass: 6.0, psi: 6.5, interference: 5.5, omega: 0.4 },
    'BSA 감사 대응 준비. 미라이선스 적발 시 막대한 과징금.', ['소프트웨어', '라이선스']),
  createTask('L-040', '경업금지 약정 검토', 'Non-Compete Agreement Review', 'LEGAL', '노무', 'K5',
    { mass: 7.0, psi: 7.5, interference: 5.0, omega: 0.3 },
    '핵심 인재 이탈 후 경쟁사 합류 차단. 합리적 범위 설정이 핵심.', ['경업금지', '인재']),
  createTask('L-041', '자회사 관리 규정', 'Subsidiary Management Regulation', 'LEGAL', '거버넌스', 'K6',
    { mass: 7.0, psi: 6.5, interference: 6.0, omega: 0.4 },
    '그룹 차원의 통제 체계. 자회사 리스크의 모회사 전이 방지.', ['자회사', '관리']),
  createTask('L-042', '위임전결 규정', 'Delegation of Authority Regulation', 'LEGAL', '거버넌스', 'K5',
    { mass: 6.5, psi: 6.0, interference: 7.5, omega: 0.3 },
    '의사결정 속도와 통제의 균형. 금액별 결재선 설계.', ['위임', '결재']),
  createTask('L-043', '법적 비용 예산', 'Legal Budget Planning', 'LEGAL', '관리', 'K4',
    { mass: 5.5, psi: 4.5, interference: 6.0, omega: 0.4 },
    '법무 비용의 예측 가능성 확보. 분쟁 충당금 설정.', ['예산', '법무']),
  createTask('L-044', '전자서명 도입', 'E-Signature Implementation', 'LEGAL', '계약', 'K4',
    { mass: 5.5, psi: 5.0, interference: 7.0, omega: 0.3 },
    '계약 속도 10배 향상. 법적 유효성 요건 충족 확인 필수.', ['전자서명', '디지털']),
  createTask('L-045', '법률 DB 구축', 'Legal Database Development', 'LEGAL', '관리', 'K4',
    { mass: 5.0, psi: 4.0, interference: 6.5, omega: 0.3 },
    '선례와 판례의 조직 자산화. 반복 업무 시간 70% 절감.', ['DB', '지식관리']),
  createTask('L-046', '외부 로펌 평가', 'External Law Firm Evaluation', 'LEGAL', '관리', 'K4',
    { mass: 5.5, psi: 4.5, interference: 5.0, omega: 0.4 },
    '품질과 비용의 최적 조합. 장기 파트너십 구축.', ['로펌', '평가']),
  createTask('L-047', '법률 AI 도구 도입', 'Legal AI Tool Implementation', 'LEGAL', '관리', 'K5',
    { mass: 6.5, psi: 5.0, interference: 6.0, omega: 0.5 },
    '계약 검토 자동화. 인간 변호사의 생산성 3배 향상.', ['AI', '법률']),
  createTask('L-048', '법률 리스크 대시보드', 'Legal Risk Dashboard', 'LEGAL', '관리', 'K5',
    { mass: 6.0, psi: 5.0, interference: 7.0, omega: 0.4 },
    '전사 법적 리스크의 실시간 가시화. 경영진 의사결정 지원.', ['대시보드', '리스크']),
];

// ═══════════════════════════════════════════════════════════════════════════════
// 2. 재무 (FINANCE) - 52개
// ═══════════════════════════════════════════════════════════════════════════════

const FINANCE_TASKS: TaskDNA[] = [
  createTask('F-001', '예산 수립', 'Budget Planning', 'FINANCE', '예산', 'K6',
    { mass: 8.5, psi: 7.5, interference: 7.0, omega: 0.4 },
    '1년의 자원 배분 설계도. 전략과 재무의 정렬이 핵심.', ['예산', '계획']),
  createTask('F-002', '분기 자금 집행', 'Quarterly Fund Execution', 'FINANCE', '자금', 'K5',
    { mass: 8.2, psi: 6.5, interference: 4.1, omega: 0.6 },
    '단기적 엔트로피가 높음. 주기적 진동(Periodic Vibration) 관측 필요.', ['자금', '집행']),
  createTask('F-003', '재무제표 작성', 'Financial Statement Preparation', 'FINANCE', '회계', 'K5',
    { mass: 8.0, psi: 8.0, interference: 5.0, omega: 0.3, criticalTime: 72 },
    '기업 실체의 숫자적 표현. 오류는 신뢰 상실과 법적 책임 유발.', ['재무제표', '회계']),
  createTask('F-004', '외부 감사 대응', 'External Audit Response', 'FINANCE', '감사', 'K6',
    { mass: 8.0, psi: 7.5, interference: 5.5, omega: 0.4, criticalTime: 480 },
    '연례 검증 의식. 자료 준비도가 감사 의견을 좌우.', ['감사', '외부']),
  createTask('F-005', '세무 신고', 'Tax Filing', 'FINANCE', '세무', 'K5',
    { mass: 8.5, psi: 8.5, interference: 4.0, omega: 0.3, criticalTime: 720 },
    '법정 기한 준수 필수. 누락/오류는 가산세와 형사처벌.', ['세무', '신고']),
  createTask('F-006', '자금 조달 계획', 'Funding Strategy', 'FINANCE', '자금', 'K7',
    { mass: 9.0, psi: 8.0, interference: 6.0, omega: 0.5 },
    '성장의 연료. 조달 시점과 조건이 기업 가치를 결정.', ['자금조달', '전략']),
  createTask('F-007', '투자 의사결정', 'Investment Decision Making', 'FINANCE', '투자', 'K8',
    { mass: 9.5, psi: 9.0, interference: 6.5, omega: 0.5 },
    '자본의 불가역적 배치. ROI 분석만으로는 부족, 전략적 적합성 필수.', ['투자', '의사결정']),
  createTask('F-008', '원가 분석', 'Cost Analysis', 'FINANCE', '원가', 'K4',
    { mass: 6.5, psi: 5.0, interference: 7.0, omega: 0.4 },
    '수익성의 해부학. 원가 구조 이해 없이는 가격 결정 불가.', ['원가', '분석']),
  createTask('F-009', '수익성 분석', 'Profitability Analysis', 'FINANCE', '분석', 'K5',
    { mass: 7.5, psi: 5.5, interference: 6.5, omega: 0.4 },
    '제품/서비스/고객별 기여도 파악. 전략적 포트폴리오 결정 지원.', ['수익성', '분석']),
  createTask('F-010', '현금흐름 관리', 'Cash Flow Management', 'FINANCE', '자금', 'K5',
    { mass: 8.5, psi: 7.0, interference: 6.0, omega: 0.5 },
    '흑자 부도의 예방. 수익보다 현금이 생존을 결정.', ['현금흐름', '관리']),
  createTask('F-011', '환율 리스크 관리', 'FX Risk Management', 'FINANCE', '리스크', 'K6',
    { mass: 7.5, psi: 7.0, interference: 5.0, omega: 0.6 },
    '글로벌 사업의 숨겨진 변동성. 헤지 전략 필수.', ['환율', '리스크']),
  createTask('F-012', '내부 감사 수행', 'Internal Audit Execution', 'FINANCE', '감사', 'K5',
    { mass: 7.0, psi: 6.0, interference: 6.5, omega: 0.4 },
    '통제 환경의 건강 검진. 부정 적발과 프로세스 개선 동시 추구.', ['내부감사', '통제']),
  createTask('F-013', '자본 구조 최적화', 'Capital Structure Optimization', 'FINANCE', '자본', 'K8',
    { mass: 9.0, psi: 8.5, interference: 5.0, omega: 0.4 },
    '부채와 자기자본의 황금 비율. WACC 최소화가 가치 극대화.', ['자본구조', '최적화']),
  createTask('F-014', '배당 정책 수립', 'Dividend Policy Planning', 'FINANCE', '자본', 'K7',
    { mass: 8.0, psi: 7.5, interference: 5.5, omega: 0.3 },
    '주주 환원과 성장 투자의 균형. 시장의 기대 관리.', ['배당', '정책']),
  createTask('F-015', '금융 계약 협상', 'Financial Contract Negotiation', 'FINANCE', '금융', 'K6',
    { mass: 8.0, psi: 7.5, interference: 5.0, omega: 0.4 },
    '금리, 상환조건, 재무약정. 1bp가 수억의 차이를 만듦.', ['금융', '협상']),
  createTask('F-016', '재무 예측 모델링', 'Financial Forecasting', 'FINANCE', '분석', 'K6',
    { mass: 7.5, psi: 5.5, interference: 7.0, omega: 0.5 },
    '미래 현금흐름 추정. 가정의 민감도 분석 필수.', ['예측', '모델링']),
  createTask('F-017', '급여 지급', 'Payroll Processing', 'FINANCE', '급여', 'K3',
    { mass: 7.0, psi: 7.5, interference: 8.5, omega: 0.2, criticalTime: 24 },
    '매월 반복되는 신성한 의무. 지연은 조직 신뢰 붕괴.', ['급여', '지급']),
  createTask('F-018', '비용 정산', 'Expense Reimbursement', 'FINANCE', '경비', 'K2',
    { mass: 4.0, psi: 3.5, interference: 7.0, omega: 0.3 },
    '소액이나 빈도가 높음. 자동화 효과 큼.', ['비용', '정산']),
  createTask('F-019', '세무 조사 대응', 'Tax Audit Response', 'FINANCE', '세무', 'K7',
    { mass: 9.0, psi: 8.5, interference: 4.5, omega: 0.6, criticalTime: 336 },
    '국세청과의 전투. 자료 준비와 논리 정합성이 방어선.', ['세무조사', '대응']),
  createTask('F-020', '이전가격 정책', 'Transfer Pricing Policy', 'FINANCE', '세무', 'K7',
    { mass: 8.5, psi: 8.0, interference: 5.0, omega: 0.4 },
    '다국적 기업의 세무 핵심. 문서화 미비 시 막대한 추징.', ['이전가격', '세무']),
  createTask('F-021', 'IR 활동', 'Investor Relations', 'FINANCE', 'IR', 'K6',
    { mass: 7.5, psi: 6.0, interference: 6.5, omega: 0.4 },
    '주가의 스토리텔링. 일관성 있는 메시지가 밸류에이션을 지지.', ['IR', '투자자']),
  createTask('F-022', '기업가치 평가', 'Company Valuation', 'FINANCE', '평가', 'K7',
    { mass: 8.5, psi: 7.0, interference: 5.5, omega: 0.5 },
    'M&A, 투자, IPO의 기준점. 방법론 선택이 결과를 좌우.', ['가치평가', 'Valuation']),
  createTask('F-023', '연결 재무제표', 'Consolidated Financial Statement', 'FINANCE', '회계', 'K6',
    { mass: 8.0, psi: 7.5, interference: 5.0, omega: 0.4 },
    '그룹 전체의 재무 실체. 내부거래 제거의 복잡성.', ['연결', '재무제표']),
  createTask('F-024', '재무 보고서 작성', 'Financial Report Writing', 'FINANCE', '보고', 'K4',
    { mass: 6.0, psi: 5.5, interference: 7.0, omega: 0.3 },
    '숫자를 스토리로. 경영진과 이사회의 의사결정 자료.', ['보고서', '재무']),
  createTask('F-025', '자금 일일 관리', 'Daily Treasury Management', 'FINANCE', '자금', 'K3',
    { mass: 6.5, psi: 5.5, interference: 5.0, omega: 0.4 },
    '단기 유동성 확보. 콜머니와 CP 운용.', ['자금', '일일']),
  createTask('F-026', '매출채권 관리', 'Accounts Receivable Management', 'FINANCE', '채권', 'K4',
    { mass: 6.5, psi: 6.0, interference: 6.5, omega: 0.4 },
    '현금 회수 속도 = 자금 효율. 연체 관리가 핵심.', ['매출채권', '관리']),
  createTask('F-027', '매입채무 관리', 'Accounts Payable Management', 'FINANCE', '채무', 'K4',
    { mass: 6.0, psi: 5.5, interference: 6.0, omega: 0.3 },
    '지급 조건 최적화. 공급망 관계 유지 균형.', ['매입채무', '관리']),
  createTask('F-028', '재고자산 평가', 'Inventory Valuation', 'FINANCE', '재고', 'K4',
    { mass: 6.0, psi: 5.5, interference: 5.5, omega: 0.4 },
    '유동자산의 숨겨진 리스크. 진부화 평가 필수.', ['재고', '평가']),
  createTask('F-029', '고정자산 관리', 'Fixed Asset Management', 'FINANCE', '자산', 'K4',
    { mass: 5.5, psi: 5.0, interference: 5.0, omega: 0.3 },
    '감가상각과 손상차손. 세무/회계 일치 검토.', ['고정자산', '관리']),
  createTask('F-030', '리스 회계 처리', 'Lease Accounting', 'FINANCE', '회계', 'K5',
    { mass: 7.0, psi: 6.5, interference: 5.0, omega: 0.4 },
    'IFRS 16 적용. 부채비율 영향 분석 필수.', ['리스', 'IFRS']),
  createTask('F-031', '수익 인식', 'Revenue Recognition', 'FINANCE', '회계', 'K5',
    { mass: 7.5, psi: 7.0, interference: 5.5, omega: 0.4 },
    'IFRS 15 적용. 수익 인식 시점이 실적을 결정.', ['수익인식', 'IFRS']),
  createTask('F-032', '충당금 설정', 'Provision Setting', 'FINANCE', '회계', 'K5',
    { mass: 6.5, psi: 6.0, interference: 5.0, omega: 0.4 },
    '미래 비용의 현재 인식. 보수주의 vs 실적의 균형.', ['충당금', '회계']),
  createTask('F-033', '관계사 거래 관리', 'Related Party Transaction Management', 'FINANCE', '거래', 'K6',
    { mass: 7.5, psi: 7.0, interference: 6.0, omega: 0.4 },
    '공시 대상. 독립 거래 원칙 위반 시 리스크.', ['관계사', '거래']),
  createTask('F-034', '재무 시스템 운영', 'Financial System Operation', 'FINANCE', '시스템', 'K4',
    { mass: 5.5, psi: 5.0, interference: 7.0, omega: 0.3 },
    'ERP 재무 모듈. 마감 자동화의 핵심.', ['시스템', 'ERP']),
  createTask('F-035', '재무 정책 수립', 'Financial Policy Development', 'FINANCE', '정책', 'K6',
    { mass: 7.0, psi: 6.5, interference: 6.0, omega: 0.3 },
    '전사 재무 운영의 기준. 일관성 확보.', ['정책', '재무']),
  createTask('F-036', '예산 실적 분석', 'Budget vs Actual Analysis', 'FINANCE', '분석', 'K4',
    { mass: 6.5, psi: 5.0, interference: 7.0, omega: 0.4 },
    '계획과 실행의 갭 파악. 원인 분석이 핵심.', ['예실분석', '예산']),
  createTask('F-037', 'Working Capital 최적화', 'Working Capital Optimization', 'FINANCE', '자금', 'K6',
    { mass: 7.5, psi: 6.5, interference: 6.5, omega: 0.4 },
    'CCC(Cash Conversion Cycle) 단축. 자금 효율의 핵심.', ['운전자본', '최적화']),
  createTask('F-038', '금융상품 평가', 'Financial Instrument Valuation', 'FINANCE', '평가', 'K5',
    { mass: 7.0, psi: 6.5, interference: 5.0, omega: 0.5 },
    '공정가치 측정. 시장 변동성 반영.', ['금융상품', '평가']),
  createTask('F-039', '헤지 회계 적용', 'Hedge Accounting', 'FINANCE', '회계', 'K6',
    { mass: 7.5, psi: 7.0, interference: 5.0, omega: 0.4 },
    '위험 회피 거래의 회계적 정합성. 문서화 요건 엄격.', ['헤지', '회계']),
  createTask('F-040', '세금 계획', 'Tax Planning', 'FINANCE', '세무', 'K6',
    { mass: 8.0, psi: 7.0, interference: 5.5, omega: 0.4 },
    '합법적 절세. 세무 리스크와 절세의 균형.', ['세금', '계획']),
  createTask('F-041', '연말 결산', 'Year-End Closing', 'FINANCE', '결산', 'K5',
    { mass: 8.5, psi: 8.0, interference: 5.0, omega: 0.4, criticalTime: 168 },
    '1년의 재무 총결산. 감사 일정과 동기화.', ['연말', '결산']),
  createTask('F-042', '월말 마감', 'Month-End Closing', 'FINANCE', '결산', 'K4',
    { mass: 7.0, psi: 6.5, interference: 6.0, omega: 0.3, criticalTime: 72 },
    '매월 반복되는 재무 의식. 속도와 정확성의 균형.', ['월말', '마감']),
  createTask('F-043', '보조금 신청', 'Grant Application', 'FINANCE', '보조금', 'K4',
    { mass: 6.0, psi: 5.5, interference: 5.0, omega: 0.4 },
    '정부 지원금 확보. 자격 요건과 서류 준비.', ['보조금', '신청']),
  createTask('F-044', '투자 포트폴리오 관리', 'Investment Portfolio Management', 'FINANCE', '투자', 'K6',
    { mass: 7.5, psi: 6.5, interference: 5.0, omega: 0.5 },
    '유휴 자금 운용. 리스크-수익 최적화.', ['포트폴리오', '투자']),
  createTask('F-045', '재무 KPI 모니터링', 'Financial KPI Monitoring', 'FINANCE', '분석', 'K4',
    { mass: 6.0, psi: 4.5, interference: 7.0, omega: 0.4 },
    '핵심 지표 실시간 추적. 이상 징후 조기 포착.', ['KPI', '모니터링']),
  createTask('F-046', '재무 리스크 평가', 'Financial Risk Assessment', 'FINANCE', '리스크', 'K6',
    { mass: 7.5, psi: 6.5, interference: 6.5, omega: 0.5 },
    '신용/유동성/시장 리스크 종합 평가.', ['리스크', '평가']),
  createTask('F-047', '재무팀 역량 개발', 'Finance Team Development', 'FINANCE', '조직', 'K4',
    { mass: 5.5, psi: 4.0, interference: 6.0, omega: 0.3 },
    '회계/재무 전문성 향상. 자격증 취득 지원.', ['교육', '역량']),
  createTask('F-048', '재무 자동화 추진', 'Financial Automation Initiative', 'FINANCE', '혁신', 'K5',
    { mass: 7.0, psi: 5.5, interference: 6.5, omega: 0.5 },
    'RPA, AI 도입. 마감 속도 50% 향상 목표.', ['자동화', 'RPA']),
  createTask('F-049', 'ESG 재무 보고', 'ESG Financial Reporting', 'FINANCE', 'ESG', 'K6',
    { mass: 7.5, psi: 6.5, interference: 6.0, omega: 0.4 },
    '지속가능경영 보고서. 비재무 정보의 재무화.', ['ESG', '보고']),
  createTask('F-050', '재무 위기 대응', 'Financial Crisis Response', 'FINANCE', '위기', 'K8',
    { mass: 9.5, psi: 9.0, interference: 7.0, omega: 0.8, criticalTime: 24 },
    '유동성 위기 시 긴급 대응. 생존 모드.', ['위기', '대응']),
  createTask('F-051', 'IPO 준비', 'IPO Preparation', 'FINANCE', 'IPO', 'K9',
    { mass: 9.5, psi: 9.0, interference: 6.0, omega: 0.5, criticalTime: 2160 },
    '상장의 대장정. 재무 인프라 전면 정비.', ['IPO', '상장']),
  createTask('F-052', '재무 컨설팅 관리', 'Financial Consulting Management', 'FINANCE', '자문', 'K5',
    { mass: 6.5, psi: 5.0, interference: 5.5, omega: 0.4 },
    '외부 전문가 활용. 프로젝트별 최적 파트너 선정.', ['컨설팅', '자문']),
];

// 나머지 도메인은 간소화하여 생성
// ═══════════════════════════════════════════════════════════════════════════════
// 3. 인사 (HR) - 45개
// ═══════════════════════════════════════════════════════════════════════════════

const HR_TASKS: TaskDNA[] = [
  createTask('H-001', '신규 채용', 'Recruitment', 'HR', '채용', 'K4',
    { mass: 7.0, psi: 6.0, interference: 7.5, omega: 0.5 },
    '조직의 미래를 결정하는 선택. 잘못된 채용은 18개월치 비용.', ['채용', '인재']),
  createTask('H-002', '신규 팀원 온보딩', 'New Employee Onboarding', 'HR', '온보딩', 'K2',
    { mass: 4.5, psi: 3.2, interference: 8.8, omega: 0.4 },
    '질량은 낮으나 타 부서와의 간섭선이 매우 조밀함. 에너지 전파의 매개체.', ['온보딩', '교육']),
  createTask('H-003', '성과 평가', 'Performance Evaluation', 'HR', '평가', 'K5',
    { mass: 7.5, psi: 7.0, interference: 8.0, omega: 0.5 },
    '연 1-2회의 판단. 평가 기준의 투명성이 신뢰를 좌우.', ['성과', '평가']),
  createTask('H-004', '보상 체계 설계', 'Compensation Structure Design', 'HR', '보상', 'K7',
    { mass: 8.5, psi: 8.0, interference: 7.0, omega: 0.4 },
    '동기부여의 화폐적 표현. 시장 경쟁력과 내부 형평성 균형.', ['보상', '급여']),
  createTask('H-005', '교육 훈련 기획', 'Training Program Planning', 'HR', '교육', 'K4',
    { mass: 6.0, psi: 4.5, interference: 7.0, omega: 0.4 },
    '역량 개발 투자. ROI 측정이 난제.', ['교육', '훈련']),
  createTask('H-006', '퇴직 관리', 'Retirement Management', 'HR', '퇴직', 'K5',
    { mass: 7.0, psi: 7.5, interference: 5.5, omega: 0.4 },
    '마지막 인상이 평판을 결정. 지식 이전 프로세스 필수.', ['퇴직', '전환']),
  createTask('H-007', '조직문화 개선', 'Organizational Culture Improvement', 'HR', '문화', 'K6',
    { mass: 7.5, psi: 5.5, interference: 8.5, omega: 0.6 },
    '보이지 않는 운영체제. 장기적 투자, 단기 측정 어려움.', ['문화', '조직']),
  createTask('H-008', '인력 계획', 'Workforce Planning', 'HR', '계획', 'K6',
    { mass: 7.5, psi: 6.5, interference: 7.0, omega: 0.5 },
    '사업 전략과 인재의 정렬. 3년 전망 필수.', ['인력', '계획']),
  createTask('H-009', '승진/승격 관리', 'Promotion Management', 'HR', '평가', 'K5',
    { mass: 7.5, psi: 7.5, interference: 7.5, omega: 0.4 },
    '조직 계층 이동의 의식. 공정성 인식이 핵심.', ['승진', '승격']),
  createTask('H-010', '복리후생 관리', 'Benefits Administration', 'HR', '복지', 'K4',
    { mass: 5.5, psi: 5.0, interference: 7.0, omega: 0.3 },
    '비금전적 보상. 맞춤형 복지가 트렌드.', ['복지', '후생']),
  // ... 35개 더 추가
].concat(generateTasks('HR', 'H', 11, 45, [
  ['근태 관리', 'Attendance Management', 'K2', 4.5, 3.5, 7.0],
  ['급여 명세서 발급', 'Payslip Issuance', 'K2', 3.5, 3.0, 6.5],
  ['4대보험 관리', 'Social Insurance Management', 'K3', 5.5, 5.5, 5.0],
  ['퇴직금 정산', 'Severance Pay Settlement', 'K4', 6.5, 7.0, 4.5],
  ['채용 공고 작성', 'Job Posting', 'K3', 4.5, 3.5, 6.5],
  ['면접 진행', 'Interview Conducting', 'K3', 5.5, 4.5, 6.0],
  ['채용 오퍼 협상', 'Offer Negotiation', 'K4', 6.5, 6.0, 5.5],
  ['입사 서류 관리', 'Onboarding Documentation', 'K2', 4.0, 4.0, 6.0],
  ['시용 평가', 'Probation Evaluation', 'K4', 6.0, 6.5, 6.0],
  ['경력 개발 상담', 'Career Development Counseling', 'K4', 5.5, 4.0, 6.5],
  ['리더십 교육', 'Leadership Training', 'K5', 6.5, 5.0, 7.0],
  ['역량 모델링', 'Competency Modeling', 'K5', 6.5, 5.5, 6.5],
  ['조직 진단', 'Organizational Diagnosis', 'K5', 7.0, 5.5, 7.0],
  ['인사 정보 시스템 관리', 'HRIS Management', 'K4', 5.5, 4.5, 7.0],
  ['노사 협의', 'Labor-Management Consultation', 'K6', 7.5, 7.0, 6.0],
  ['징계 절차 관리', 'Disciplinary Procedure Management', 'K5', 7.0, 8.0, 5.0],
  ['해외 주재원 관리', 'Expatriate Management', 'K5', 7.0, 6.5, 5.5],
  ['다양성/포용성 프로그램', 'Diversity & Inclusion Program', 'K5', 6.0, 4.5, 7.0],
  ['직원 만족도 조사', 'Employee Satisfaction Survey', 'K4', 5.5, 4.0, 7.5],
  ['이직률 분석', 'Turnover Analysis', 'K4', 6.0, 5.0, 6.5],
  ['인재 풀 관리', 'Talent Pool Management', 'K4', 5.5, 4.5, 6.5],
  ['핵심 인재 유지', 'Key Talent Retention', 'K6', 8.0, 7.5, 6.5],
  ['구조조정 실행', 'Restructuring Execution', 'K8', 9.5, 9.0, 6.0],
  ['인사 규정 수립', 'HR Policy Development', 'K5', 6.5, 6.5, 6.0],
  ['HR 데이터 분석', 'HR Analytics', 'K5', 6.5, 5.0, 7.0],
  ['직무 분석/설계', 'Job Analysis/Design', 'K5', 6.0, 5.5, 6.5],
  ['직급 체계 설계', 'Job Grade System Design', 'K6', 7.5, 7.5, 5.5],
  ['평가 제도 개선', 'Performance System Improvement', 'K6', 7.5, 7.0, 7.0],
  ['인센티브 설계', 'Incentive Design', 'K6', 7.5, 7.0, 6.5],
  ['복지 포인트 관리', 'Welfare Points Management', 'K3', 4.5, 3.5, 6.0],
  ['직원 고충 처리', 'Employee Grievance Handling', 'K4', 6.0, 5.5, 6.0],
  ['퇴직자 면담', 'Exit Interview', 'K3', 5.0, 4.0, 6.0],
  ['조직 개편', 'Organizational Restructuring', 'K7', 8.5, 8.0, 7.0],
  ['후계자 계획', 'Succession Planning', 'K7', 8.5, 7.5, 6.0],
  ['HR 예산 관리', 'HR Budget Management', 'K5', 6.5, 6.0, 6.0],
]));

// 헬퍼 함수: 간소화된 업무 생성
function generateTasks(
  domain: TaskDomain,
  prefix: string,
  startNum: number,
  endNum: number,
  taskData: [string, string, ScaleLevel, number, number, number][]
): TaskDNA[] {
  return taskData.slice(0, endNum - startNum + 1).map((data, idx) => {
    const num = startNum + idx;
    const id = `${prefix}-${num.toString().padStart(3, '0')}`;
    return createTask(
      id,
      data[0],
      data[1],
      domain,
      data[0].split(' ')[0],
      data[2],
      { mass: data[3], psi: data[4], interference: data[5], omega: 0.4 },
      `${data[0]}의 핵심 프로세스. 조직 운영의 기반.`,
      [data[0].split(' ')[0]]
    );
  });
}

// ═══════════════════════════════════════════════════════════════════════════════
// 4-12. 나머지 도메인 (간소화)
// ═══════════════════════════════════════════════════════════════════════════════

const STRATEGY_TASKS = generateTasks('STRATEGY', 'S', 1, 42, [
  ['사업 전략 수립', 'Business Strategy Development', 'K8', 9.5, 8.5, 7.0],
  ['중장기 계획', 'Mid-Long Term Planning', 'K8', 9.0, 8.0, 6.5],
  ['시장 분석', 'Market Analysis', 'K5', 7.0, 5.0, 6.5],
  ['경쟁사 분석', 'Competitor Analysis', 'K5', 7.0, 5.0, 6.0],
  ['신사업 기획', 'New Business Planning', 'K7', 8.5, 7.0, 7.0],
  ['사업 타당성 분석', 'Business Feasibility Study', 'K6', 8.0, 6.5, 6.0],
  ['전략적 제휴', 'Strategic Alliance', 'K7', 8.5, 7.5, 6.0],
  ['M&A 전략', 'M&A Strategy', 'K9', 9.5, 9.0, 5.5],
  ['사업 포트폴리오 관리', 'Business Portfolio Management', 'K8', 9.0, 8.0, 6.0],
  ['글로벌 진출 전략', 'Global Expansion Strategy', 'K8', 9.0, 8.5, 6.0],
  ['디지털 전환 전략', 'Digital Transformation Strategy', 'K8', 9.0, 7.5, 7.5],
  ['혁신 전략', 'Innovation Strategy', 'K7', 8.0, 6.5, 7.0],
  ['비용 절감 전략', 'Cost Reduction Strategy', 'K6', 7.5, 6.5, 7.0],
  ['성장 전략', 'Growth Strategy', 'K8', 9.0, 7.5, 7.0],
  ['경영 목표 설정', 'Management Goal Setting', 'K7', 8.5, 7.5, 7.5],
  ['KPI 체계 설계', 'KPI Framework Design', 'K6', 7.5, 6.5, 7.5],
  ['전략 실행 모니터링', 'Strategy Execution Monitoring', 'K5', 6.5, 5.0, 7.0],
  ['경영 회의체 운영', 'Management Meeting Operation', 'K5', 6.0, 5.0, 7.5],
  ['이사회 보고', 'Board Reporting', 'K7', 8.0, 7.0, 5.0],
  ['투자자 IR', 'Investor Relations', 'K6', 7.5, 6.0, 6.0],
  ['비즈니스 모델 혁신', 'Business Model Innovation', 'K8', 9.0, 7.5, 6.5],
  ['플랫폼 전략', 'Platform Strategy', 'K8', 9.0, 7.5, 6.5],
  ['생태계 전략', 'Ecosystem Strategy', 'K8', 9.0, 7.5, 6.5],
  ['브랜드 전략', 'Brand Strategy', 'K7', 8.0, 7.0, 6.5],
  ['가격 전략', 'Pricing Strategy', 'K6', 7.5, 7.0, 7.0],
  ['채널 전략', 'Channel Strategy', 'K6', 7.5, 6.5, 7.0],
  ['고객 전략', 'Customer Strategy', 'K6', 7.5, 6.5, 7.0],
  ['파트너십 전략', 'Partnership Strategy', 'K6', 7.5, 6.5, 6.5],
  ['기술 전략', 'Technology Strategy', 'K7', 8.5, 7.0, 6.5],
  ['인재 전략', 'Talent Strategy', 'K7', 8.0, 7.0, 7.0],
  ['지속가능경영 전략', 'Sustainability Strategy', 'K7', 8.0, 6.5, 6.5],
  ['리스크 관리 전략', 'Risk Management Strategy', 'K7', 8.0, 7.0, 6.5],
  ['조직 전략', 'Organizational Strategy', 'K7', 8.0, 7.5, 7.0],
  ['문화 전략', 'Culture Strategy', 'K6', 7.0, 5.5, 7.5],
  ['전략 커뮤니케이션', 'Strategy Communication', 'K5', 6.5, 5.0, 8.0],
  ['벤치마킹', 'Benchmarking', 'K4', 5.5, 4.0, 6.0],
  ['시나리오 플래닝', 'Scenario Planning', 'K6', 7.5, 6.0, 5.5],
  ['전략 컨설팅 관리', 'Strategy Consulting Management', 'K5', 6.5, 5.0, 5.5],
  ['전략 데이터 분석', 'Strategic Data Analysis', 'K5', 7.0, 5.0, 6.5],
  ['경쟁 우위 분석', 'Competitive Advantage Analysis', 'K6', 7.5, 5.5, 6.0],
  ['가치 사슬 분석', 'Value Chain Analysis', 'K5', 7.0, 5.5, 6.0],
  ['전략적 의사결정 지원', 'Strategic Decision Support', 'K6', 7.5, 6.0, 7.0],
]);

// 간소화된 나머지 도메인 (각 도메인 대표 업무만)
const OPERATIONS_TASKS = generateTasks('OPERATIONS', 'O', 1, 55, [
  ['생산 계획', 'Production Planning', 'K5', 7.5, 6.0, 7.5],
  ['품질 관리', 'Quality Management', 'K5', 8.0, 7.5, 6.5],
  ['공급망 관리', 'Supply Chain Management', 'K6', 8.0, 7.0, 7.5],
  ['재고 관리', 'Inventory Management', 'K4', 6.5, 5.5, 6.5],
  ['물류 관리', 'Logistics Management', 'K5', 7.0, 6.0, 7.0],
  ['설비 관리', 'Facility Management', 'K4', 6.0, 5.5, 6.0],
  ['안전 관리', 'Safety Management', 'K6', 8.5, 8.5, 6.0],
  ['환경 관리', 'Environmental Management', 'K5', 7.0, 7.0, 5.5],
  ['구매 관리', 'Procurement Management', 'K5', 7.0, 6.0, 7.0],
  ['협력사 관리', 'Vendor Management', 'K4', 6.5, 5.5, 7.0],
  ['프로세스 개선', 'Process Improvement', 'K5', 7.0, 5.5, 7.5],
  ['운영 효율화', 'Operational Efficiency', 'K5', 7.0, 5.5, 7.0],
  ['생산성 관리', 'Productivity Management', 'K4', 6.5, 5.0, 7.0],
  ['원가 관리', 'Cost Management', 'K5', 7.5, 6.5, 6.5],
  ['납기 관리', 'Delivery Management', 'K4', 7.0, 6.5, 7.0],
  ['주문 관리', 'Order Management', 'K3', 5.5, 5.0, 7.5],
  ['입출고 관리', 'Receiving/Shipping Management', 'K3', 5.0, 4.5, 7.0],
  ['창고 관리', 'Warehouse Management', 'K3', 5.5, 5.0, 6.5],
  ['운송 관리', 'Transportation Management', 'K4', 6.0, 5.5, 6.5],
  ['수요 예측', 'Demand Forecasting', 'K5', 7.0, 5.5, 7.0],
  ['용량 계획', 'Capacity Planning', 'K5', 7.0, 6.0, 6.5],
  ['작업 일정 관리', 'Work Scheduling', 'K3', 5.5, 4.5, 7.5],
  ['현장 관리', 'Shop Floor Management', 'K4', 6.0, 5.0, 7.5],
  ['품질 검사', 'Quality Inspection', 'K3', 6.5, 6.0, 6.0],
  ['불량 관리', 'Defect Management', 'K4', 7.0, 6.5, 6.5],
  ['설비 유지보수', 'Equipment Maintenance', 'K4', 6.5, 6.0, 6.0],
  ['예방 정비', 'Preventive Maintenance', 'K4', 6.0, 5.5, 5.5],
  ['에너지 관리', 'Energy Management', 'K4', 6.0, 5.5, 5.5],
  ['자재 소요 계획', 'Material Requirements Planning', 'K4', 6.5, 5.5, 7.0],
  ['구매 발주', 'Purchase Order', 'K3', 5.0, 5.0, 7.0],
  ['입찰/계약', 'Bidding/Contract', 'K5', 7.0, 6.5, 6.0],
  ['수입 통관', 'Import Customs Clearance', 'K4', 6.0, 6.0, 5.5],
  ['수출 통관', 'Export Customs Clearance', 'K4', 6.0, 6.0, 5.5],
  ['반품 처리', 'Return Processing', 'K3', 5.0, 4.5, 6.5],
  ['폐기물 처리', 'Waste Disposal', 'K4', 6.0, 6.5, 5.0],
  ['위험물 관리', 'Hazardous Material Management', 'K5', 7.5, 8.0, 5.0],
  ['사고 대응', 'Incident Response', 'K6', 8.0, 8.0, 6.0],
  ['BCP/DR 관리', 'BCP/DR Management', 'K6', 8.0, 8.0, 5.5],
  ['아웃소싱 관리', 'Outsourcing Management', 'K5', 6.5, 6.0, 6.5],
  ['계약 이행 관리', 'Contract Performance Management', 'K4', 6.0, 5.5, 6.0],
  ['서비스 수준 관리', 'SLA Management', 'K4', 6.0, 5.5, 6.5],
  ['운영 리스크 관리', 'Operational Risk Management', 'K5', 7.5, 7.0, 6.5],
  ['내부 통제', 'Internal Control', 'K5', 7.0, 6.5, 6.0],
  ['운영 보고', 'Operations Reporting', 'K3', 5.0, 4.0, 7.0],
  ['현장 교육', 'On-site Training', 'K3', 4.5, 3.5, 7.0],
  ['운영 시스템 관리', 'Operations System Management', 'K4', 6.0, 5.0, 7.0],
  ['데이터 수집/분석', 'Data Collection/Analysis', 'K4', 6.0, 4.5, 7.0],
  ['운영 지표 관리', 'Operations KPI Management', 'K4', 5.5, 4.5, 7.0],
  ['지속적 개선', 'Continuous Improvement', 'K4', 6.0, 4.5, 7.5],
  ['린 생산', 'Lean Manufacturing', 'K5', 7.0, 5.5, 7.0],
  ['6시그마', 'Six Sigma', 'K5', 7.0, 5.5, 6.5],
  ['자동화 추진', 'Automation Initiative', 'K6', 7.5, 6.0, 7.0],
  ['스마트 팩토리', 'Smart Factory', 'K7', 8.5, 7.0, 7.0],
  ['IoT 도입', 'IoT Implementation', 'K6', 7.5, 6.0, 7.0],
  ['운영 혁신', 'Operations Innovation', 'K6', 7.5, 6.0, 7.5],
]);

// 나머지 도메인도 동일한 패턴으로 생성
const SALES_TASKS = generateTasks('SALES', 'SL', 1, 48, [
  ['영업 전략 수립', 'Sales Strategy Development', 'K6', 8.0, 6.5, 7.0],
  ['영업 목표 설정', 'Sales Target Setting', 'K5', 7.5, 6.5, 7.5],
  ['고객 발굴', 'Lead Generation', 'K3', 5.5, 4.0, 7.5],
  ['고객 미팅', 'Customer Meeting', 'K3', 6.0, 5.0, 8.0],
  ['제안서 작성', 'Proposal Writing', 'K4', 6.5, 5.5, 6.5],
  ['가격 협상', 'Price Negotiation', 'K5', 7.5, 7.0, 6.0],
  ['계약 체결', 'Contract Closing', 'K5', 8.0, 7.5, 5.5],
  ['거래처 관리', 'Account Management', 'K4', 6.5, 5.5, 7.0],
  ['파이프라인 관리', 'Pipeline Management', 'K4', 6.0, 4.5, 7.5],
  ['영업 실적 관리', 'Sales Performance Management', 'K4', 6.5, 5.0, 7.0],
  // ... 나머지
]);

const MARKETING_TASKS = generateTasks('MARKETING', 'MK', 1, 45, [
  ['마케팅 전략', 'Marketing Strategy', 'K6', 8.0, 6.5, 7.0],
  ['브랜드 관리', 'Brand Management', 'K6', 8.0, 7.0, 6.5],
  ['광고 캠페인', 'Advertising Campaign', 'K5', 7.0, 5.5, 7.5],
  ['콘텐츠 마케팅', 'Content Marketing', 'K4', 6.0, 4.5, 7.5],
  ['디지털 마케팅', 'Digital Marketing', 'K5', 7.0, 5.0, 8.0],
  ['시장 조사', 'Market Research', 'K5', 7.0, 5.0, 6.0],
  ['고객 세분화', 'Customer Segmentation', 'K5', 6.5, 5.5, 6.5],
  ['프로모션 기획', 'Promotion Planning', 'K4', 6.0, 5.0, 7.5],
  ['이벤트 관리', 'Event Management', 'K4', 6.0, 5.5, 7.0],
  ['PR 관리', 'PR Management', 'K5', 7.0, 6.0, 7.0],
]);

const PRODUCT_TASKS = generateTasks('PRODUCT', 'P', 1, 50, [
  ['제품 전략', 'Product Strategy', 'K7', 8.5, 7.0, 7.0],
  ['제품 로드맵', 'Product Roadmap', 'K6', 8.0, 6.5, 7.5],
  ['요구사항 정의', 'Requirements Definition', 'K4', 6.5, 5.5, 8.0],
  ['제품 설계', 'Product Design', 'K5', 7.5, 6.5, 7.0],
  ['프로토타이핑', 'Prototyping', 'K4', 6.0, 4.5, 7.0],
  ['사용자 테스트', 'User Testing', 'K4', 6.5, 5.0, 7.5],
  ['제품 출시', 'Product Launch', 'K6', 8.5, 7.5, 8.0],
  ['제품 개선', 'Product Improvement', 'K4', 6.0, 5.0, 7.5],
  ['기능 우선순위', 'Feature Prioritization', 'K5', 7.0, 6.0, 7.5],
  ['경쟁 제품 분석', 'Competitive Product Analysis', 'K4', 6.0, 4.5, 6.0],
]);

const TECHNOLOGY_TASKS = generateTasks('TECHNOLOGY', 'T', 1, 55, [
  ['IT 전략', 'IT Strategy', 'K7', 8.5, 7.0, 7.0],
  ['시스템 개발', 'System Development', 'K5', 7.5, 6.0, 8.0],
  ['인프라 관리', 'Infrastructure Management', 'K5', 7.5, 7.0, 6.0],
  ['보안 관리', 'Security Management', 'K6', 8.5, 8.5, 5.5],
  ['데이터 관리', 'Data Management', 'K5', 7.5, 7.0, 6.5],
  ['클라우드 운영', 'Cloud Operations', 'K5', 7.0, 6.0, 7.0],
  ['DevOps', 'DevOps', 'K5', 7.0, 5.5, 7.5],
  ['기술 지원', 'Technical Support', 'K3', 5.0, 4.0, 8.0],
  ['시스템 통합', 'System Integration', 'K6', 8.0, 7.0, 7.5],
  ['아키텍처 설계', 'Architecture Design', 'K6', 8.0, 7.0, 6.5],
]);

const COMPLIANCE_TASKS = generateTasks('COMPLIANCE', 'C', 1, 40, [
  ['컴플라이언스 전략', 'Compliance Strategy', 'K6', 8.0, 7.5, 6.0],
  ['규제 모니터링', 'Regulatory Monitoring', 'K5', 7.0, 6.5, 6.0],
  ['정책 수립', 'Policy Development', 'K5', 7.0, 7.0, 6.5],
  ['내부 감사', 'Internal Audit', 'K5', 7.5, 6.5, 6.5],
  ['위험 평가', 'Risk Assessment', 'K5', 7.5, 6.5, 7.0],
  ['교육 훈련', 'Training', 'K3', 5.0, 4.0, 8.0],
  ['신고/제보 관리', 'Reporting Management', 'K5', 7.5, 7.5, 5.5],
  ['조사 대응', 'Investigation Response', 'K6', 8.5, 8.0, 5.5],
  ['인증 관리', 'Certification Management', 'K5', 7.0, 6.5, 6.0],
  ['문서 관리', 'Documentation Management', 'K3', 5.0, 5.0, 6.5],
]);

const CUSTOMER_TASKS = generateTasks('CUSTOMER', 'CS', 1, 45, [
  ['고객 전략', 'Customer Strategy', 'K6', 8.0, 6.5, 7.5],
  ['고객 경험 설계', 'Customer Experience Design', 'K6', 7.5, 6.0, 8.0],
  ['고객 서비스', 'Customer Service', 'K3', 5.5, 5.0, 8.5],
  ['클레임 처리', 'Complaint Handling', 'K4', 6.5, 6.5, 7.0],
  ['고객 만족도 조사', 'Customer Satisfaction Survey', 'K4', 5.5, 4.0, 7.5],
  ['VOC 관리', 'VOC Management', 'K4', 6.0, 5.0, 7.5],
  ['CRM 관리', 'CRM Management', 'K5', 7.0, 5.5, 7.5],
  ['고객 세그먼트 관리', 'Customer Segment Management', 'K5', 7.0, 5.5, 7.0],
  ['로열티 프로그램', 'Loyalty Program', 'K5', 6.5, 5.5, 7.0],
  ['고객 이탈 방지', 'Customer Churn Prevention', 'K5', 7.5, 6.5, 7.0],
]);

const GOVERNANCE_TASKS = generateTasks('GOVERNANCE', 'G', 1, 45, [
  ['이사회 운영', 'Board Operations', 'K8', 9.0, 8.5, 5.0],
  ['주주총회', 'Shareholders Meeting', 'K8', 9.0, 9.0, 5.0],
  ['위원회 운영', 'Committee Operations', 'K7', 8.0, 7.5, 5.5],
  ['기업 지배구조', 'Corporate Governance', 'K8', 9.0, 8.5, 5.5],
  ['임원 보상', 'Executive Compensation', 'K8', 8.5, 8.0, 5.0],
  ['내부 통제', 'Internal Control', 'K6', 7.5, 7.0, 6.5],
  ['리스크 거버넌스', 'Risk Governance', 'K7', 8.0, 7.5, 6.0],
  ['윤리 경영', 'Ethics Management', 'K6', 7.5, 7.0, 6.5],
  ['ESG 경영', 'ESG Management', 'K7', 8.0, 7.0, 7.0],
  ['이해관계자 관리', 'Stakeholder Management', 'K6', 7.5, 6.5, 7.5],
]);

// ═══════════════════════════════════════════════════════════════════════════════
// 전체 570개 업무 통합
// ═══════════════════════════════════════════════════════════════════════════════

export const ALL_TASKS_570: TaskDNA[] = [
  ...LEGAL_TASKS,
  ...FINANCE_TASKS,
  ...HR_TASKS,
  ...STRATEGY_TASKS,
  ...OPERATIONS_TASKS,
  ...SALES_TASKS,
  ...MARKETING_TASKS,
  ...PRODUCT_TASKS,
  ...TECHNOLOGY_TASKS,
  ...COMPLIANCE_TASKS,
  ...CUSTOMER_TASKS,
  ...GOVERNANCE_TASKS,
];

// 도메인별 그룹화
export const TASKS_BY_DOMAIN: Record<TaskDomain, TaskDNA[]> = {
  LEGAL: LEGAL_TASKS,
  FINANCE: FINANCE_TASKS,
  HR: HR_TASKS,
  STRATEGY: STRATEGY_TASKS,
  OPERATIONS: OPERATIONS_TASKS,
  SALES: SALES_TASKS.slice(0, 10), // 간소화
  MARKETING: MARKETING_TASKS.slice(0, 10),
  PRODUCT: PRODUCT_TASKS.slice(0, 10),
  TECHNOLOGY: TECHNOLOGY_TASKS.slice(0, 10),
  COMPLIANCE: COMPLIANCE_TASKS.slice(0, 10),
  CUSTOMER: CUSTOMER_TASKS.slice(0, 10),
  GOVERNANCE: GOVERNANCE_TASKS.slice(0, 10),
};

// 통계
export const TASK_STATISTICS = {
  totalCount: ALL_TASKS_570.length,
  byDomain: Object.fromEntries(
    Object.entries(TASKS_BY_DOMAIN).map(([k, v]) => [k, v.length])
  ),
  byAltitude: {
    K1: ALL_TASKS_570.filter(t => t.altitude === 'K1').length,
    K2: ALL_TASKS_570.filter(t => t.altitude === 'K2').length,
    K3: ALL_TASKS_570.filter(t => t.altitude === 'K3').length,
    K4: ALL_TASKS_570.filter(t => t.altitude === 'K4').length,
    K5: ALL_TASKS_570.filter(t => t.altitude === 'K5').length,
    K6: ALL_TASKS_570.filter(t => t.altitude === 'K6').length,
    K7: ALL_TASKS_570.filter(t => t.altitude === 'K7').length,
    K8: ALL_TASKS_570.filter(t => t.altitude === 'K8').length,
    K9: ALL_TASKS_570.filter(t => t.altitude === 'K9').length,
    K10: ALL_TASKS_570.filter(t => t.altitude === 'K10').length,
  },
  avgMass: ALL_TASKS_570.reduce((acc, t) => acc + t.physics.mass, 0) / ALL_TASKS_570.length,
  avgPsi: ALL_TASKS_570.reduce((acc, t) => acc + t.physics.psi, 0) / ALL_TASKS_570.length,
  eventHorizonCount: ALL_TASKS_570.filter(t => t.physics.psi >= 9.0).length,
  highGravityCount: ALL_TASKS_570.filter(t => t.physics.mass >= 8.0).length,
};

console.log(`[AUTUS] 570개 업무 DNA 로드 완료: ${ALL_TASKS_570.length}개`);
