/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * AUTUS ExecutorCard - 실행자(K1~K2) 전용 카드
 * "생각하지 않게 한다. 다음 행동만 보여준다."
 * ═══════════════════════════════════════════════════════════════════════════════
 */

import React, { useState } from 'react';
import { 
  BaseCard, 
  CardInfoRow, 
  CardStatusBadge, 
  CardAlert, 
  CardActions, 
  CardButton 
} from './BaseCard';

// ═══════════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════════

export interface NextAction {
  id: string;
  task: string;
  standard: string;
  status: 'pending' | 'in_progress' | 'completed';
  warning?: string;
  metadata?: {
    location?: string;
    deadline?: string;
    priority?: 'low' | 'normal' | 'high';
  };
}

interface ExecutorCardProps {
  action: NextAction;
  onContinue: (actionId: string) => void;
  onPause?: (actionId: string) => void;
  onComplete?: (actionId: string) => void;
  onReportIssue?: (actionId: string) => void;
}

// ═══════════════════════════════════════════════════════════════════════════════
// NextActionCard - 다음 작업 카드
// ═══════════════════════════════════════════════════════════════════════════════

export function NextActionCard({
  action,
  onContinue,
  onPause,
  onComplete,
  onReportIssue,
}: ExecutorCardProps) {
  const [isLoading, setIsLoading] = useState(false);

  const handleContinue = async () => {
    setIsLoading(true);
    try {
      await onContinue(action.id);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <BaseCard 
      type="action"
      title={action.task}
      priority={action.warning ? 'high' : 'normal'}
    >
      {/* 기준 표시 */}
      <CardInfoRow 
        label="기준" 
        value={action.standard} 
        highlight 
      />

      {/* 현재 상태 */}
      <div className="flex items-center justify-between">
        <span className="text-gray-400 text-sm">현재 상태</span>
        <CardStatusBadge status={action.status} />
      </div>

      {/* 메타데이터 */}
      {action.metadata?.location && (
        <CardInfoRow 
          label="위치" 
          value={action.metadata.location} 
        />
      )}

      {/* 경고 */}
      {action.warning && (
        <CardAlert type="warning" message={action.warning} />
      )}

      {/* 액션 버튼 */}
      <CardActions variant="vertical">
        <CardButton 
          variant="primary" 
          onClick={handleContinue}
          loading={isLoading}
          fullWidth
        >
          {action.status === 'pending' ? '작업 시작' : '조정 후 계속'}
        </CardButton>
        
        {onComplete && action.status === 'in_progress' && (
          <CardButton 
            variant="secondary" 
            onClick={() => onComplete(action.id)}
            fullWidth
          >
            작업 완료
          </CardButton>
        )}
      </CardActions>
    </BaseCard>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// AutoReportCard - 자동 보고 완료 카드
// ═══════════════════════════════════════════════════════════════════════════════

interface AutoReportCardProps {
  reportId: string;
  photoCount: number;
  workDuration: string;
  autoGenerated: boolean;
  onConfirm: () => void;
  onEdit?: () => void;
}

export function AutoReportCard({
  reportId,
  photoCount,
  workDuration,
  autoGenerated,
  onConfirm,
  onEdit,
}: AutoReportCardProps) {
  return (
    <BaseCard 
      type="success"
      title="보고서 생성 완료"
    >
      <CardInfoRow label="사진" value={`${photoCount}장`} />
      <CardInfoRow label="작업 시간" value={workDuration} />
      
      {autoGenerated && (
        <CardAlert 
          type="info" 
          message="작업 시간이 자동으로 기록되었습니다" 
        />
      )}

      <CardActions>
        <CardButton variant="primary" onClick={onConfirm} fullWidth>
          확인
        </CardButton>
        {onEdit && (
          <CardButton variant="ghost" onClick={onEdit}>
            수정
          </CardButton>
        )}
      </CardActions>
    </BaseCard>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// RiskAlertCard - 위험 경고 카드 (ENGINE B)
// ═══════════════════════════════════════════════════════════════════════════════

interface RiskAlertCardProps {
  riskType: 'mistake' | 'safety' | 'deadline' | 'quality';
  message: string;
  suggestion?: string;
  onAcknowledge: () => void;
  onIgnore?: () => void;
}

export function RiskAlertCard({
  riskType,
  message,
  suggestion,
  onAcknowledge,
  onIgnore,
}: RiskAlertCardProps) {
  const riskLabels = {
    mistake: '실수 위험',
    safety: '안전 경고',
    deadline: '기한 위험',
    quality: '품질 위험',
  };

  return (
    <BaseCard 
      type="warning"
      title={riskLabels[riskType]}
      priority="high"
    >
      <CardAlert type="error" message={message} />
      
      {suggestion && (
        <div className="p-3 bg-blue-500/10 rounded-lg border border-blue-500/30">
          <span className="text-sm text-blue-400">💡 권장: {suggestion}</span>
        </div>
      )}

      <CardActions>
        <CardButton variant="primary" onClick={onAcknowledge} fullWidth>
          확인했습니다
        </CardButton>
        {onIgnore && (
          <CardButton variant="ghost" onClick={onIgnore}>
            무시
          </CardButton>
        )}
      </CardActions>
    </BaseCard>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// TaskDeletedCard - 업무 삭제 알림 카드
// ═══════════════════════════════════════════════════════════════════════════════

interface TaskDeletedCardProps {
  taskName: string;
  reason: string;
  onConfirm: () => void;
}

export function TaskDeletedCard({
  taskName,
  reason,
  onConfirm,
}: TaskDeletedCardProps) {
  return (
    <BaseCard 
      type="info"
      title="업무 삭제됨"
    >
      <div className="text-center py-4">
        <div className="text-4xl mb-2">🎉</div>
        <p className="text-lg font-medium text-white mb-2">
          "{taskName}"
        </p>
        <p className="text-gray-400">
          이건 이제 안 해도 됩니다
        </p>
      </div>

      <CardAlert type="success" message={reason} />

      <CardButton variant="primary" onClick={onConfirm} fullWidth>
        확인
      </CardButton>
    </BaseCard>
  );
}

export default NextActionCard;
