

from packs.security.enforcer import Risk, RiskCategory, Severity, enforcer, ConstitutionViolationError
# 핵심 Risk 클래스 직접 정의 (최소 골격)
class PIIStorageRisk(Risk):
    def __init__(self) -> None:
        super().__init__(
            name="PII Storage Attempt",
            category=RiskCategory.SECURITY,
            severity=Severity.CRITICAL,
            description="Constitution Article II violation: PII detected in storage",
            prevention=self.prevent,
            detection=self.detect,
            response=self.respond,
            recovery=self.recover
        )
    def prevent(self) -> None: pass
    def detect(self) -> bool: return False
    def respond(self) -> None: pass
    def recover(self) -> None: pass

class CodeInjectionRisk(Risk):
    def __init__(self) -> None:
        super().__init__(
            name="Code Injection Attack",
            category=RiskCategory.SECURITY,
            severity=Severity.CRITICAL,
            description="Constitution Article II violation: Malicious code generated by AI",
            prevention=self.prevent,
            detection=self.detect,
            response=self.respond,
            recovery=self.recover
        )
    def prevent(self) -> None: pass
    def detect(self) -> bool: return False
    def respond(self) -> None: pass
    def recover(self) -> None: pass

# --- 추가: RateLimitRisk, DatabaseCorruptionRisk, PerformanceBudgetRisk ---
class RateLimitRisk(Risk):
    def __init__(self) -> None:
        super().__init__(
            name="API Rate Limit",
            category=RiskCategory.API,
            severity=Severity.HIGH,
            description="Article IV violation: API rate limit exceeded or approaching",
            prevention=self.prevent,
            detection=self.detect,
            response=self.respond,
            recovery=self.recover
        )
    def prevent(self) -> None: pass
    def detect(self) -> bool: return False
    def respond(self) -> None: pass
    def recover(self) -> None: pass

class DatabaseCorruptionRisk(Risk):
    def __init__(self) -> None:
        super().__init__(
            name="Database Corruption",
            category=RiskCategory.DATA,
            severity=Severity.CRITICAL,
            description="Article IV violation: DuckDB database file corrupted",
            prevention=self.prevent,
            detection=self.detect,
            response=self.respond,
            recovery=self.recover
        )
    def prevent(self) -> None: pass
    def detect(self) -> bool: return False
    def respond(self) -> None: pass
    def recover(self) -> None: pass

class PerformanceBudgetRisk(Risk):
    def __init__(self) -> None:
        super().__init__(
            name="Performance Budget Exceeded",
            category=RiskCategory.PERFORMANCE,
            severity=Severity.HIGH,
            description="Article IV violation: Performance budget (memory/disk) exceeded",
            prevention=self.prevent,
            detection=self.detect,
            response=self.respond,
            recovery=self.recover
        )
    def prevent(self) -> None: pass
    def detect(self) -> bool: return False
    def respond(self) -> None: pass
    def recover(self) -> None: pass


from pathlib import Path
import logging

"""
from __future__ import annotations

AUTUS 핵심 리스크 정의

Constitution을 지키는 5개 Critical 리스크
"""

logger = logging.getLogger(__name__)


# ═══════════════════════════════════════════
# Risk 1: PII 저장 시도 (Article II 위반)
# ═══════════════════════════════════════════

def prevent_pii():
    """PII 저장 방지"""
    logger.debug("PII prevention active")


def detect_pii() -> bool:
    """PII 감지"""
    try:
        from protocols.memory.store import MemoryStore

        # 간단한 감지: 최근 저장된 데이터 스캔
        store = MemoryStore()

        # preferences 테이블 스캔
        results = store.conn.execute(
            "SELECT key, value FROM preferences ORDER BY updated_at DESC LIMIT 100"
        ).fetchall()

        from protocols.memory.pii_validator import PIIValidator

        for key, value in results:
            try:
                PIIValidator.validate(key, value)
            except Exception:
                # PII 발견
                logger.warning(f"PII detected in stored data: key={key}")
                return True

        return False
    except Exception as e:
        logger.error(f"PII detection error: {e}")
        return False


def respond_to_pii():
    """PII 대응"""
    logger.critical("🚨 CONSTITUTION VIOLATION: PII detected in storage")
    raise ConstitutionViolationError(
        "Article II violated: PII storage attempted. "
        "This is a critical security violation."
    )


def recover_from_pii():
    """PII 복구"""
    logger.info("Recovering from PII violation...")

    try:
        from protocols.memory.recovery import RecoveryManager
        from pathlib import Path

        # 최신 체크포인트에서 복구
        checkpoints = RecoveryManager.list_checkpoints()
        if checkpoints:
            RecoveryManager.restore_from_checkpoint(
                checkpoints[0],
                Path(".autus/memory/memory.db")
            )
            logger.info("Recovered from checkpoint")
        else:
            logger.warning("No checkpoint available for recovery")
    except Exception as e:
        logger.error(f"PII recovery failed: {e}")



def register_core_risks():
    """핵심 Risk 5종을 중복 없이 등록"""
    # 중복 방지: 이미 등록된 이름은 건너뜀
    registered = set(r.name for r in enforcer.risks)

    pii_risk = Risk(
        name="PII Storage Attempt",
        category=RiskCategory.SECURITY,
        severity=Severity.CRITICAL,
        description="Constitution Article II violation: PII detected in storage",
        prevention=PIIStorageRisk().prevent,
        detection=PIIStorageRisk().detect,
        response=PIIStorageRisk().respond,
        recovery=PIIStorageRisk().recover
    )
    if pii_risk.name not in registered:
        enforcer.register_risk(pii_risk)

    code_injection_risk = Risk(
        name="Code Injection Attack",
        category=RiskCategory.SECURITY,
        severity=Severity.CRITICAL,
        description="Constitution Article II violation: Malicious code generated by AI",
        prevention=CodeInjectionRisk().prevent,
        detection=CodeInjectionRisk().detect,
        response=CodeInjectionRisk().respond,
        recovery=CodeInjectionRisk().recover
    )
    if code_injection_risk.name not in registered:
        enforcer.register_risk(code_injection_risk)

    rate_limit_risk = Risk(
        name="API Rate Limit",
        category=RiskCategory.API,
        severity=Severity.HIGH,
        description="Article IV violation: API rate limit exceeded or approaching",
        prevention=RateLimitRisk().prevent,
        detection=RateLimitRisk().detect,
        response=RateLimitRisk().respond,
        recovery=RateLimitRisk().recover
    )
    if rate_limit_risk.name not in registered:
        enforcer.register_risk(rate_limit_risk)

    db_corruption_risk = Risk(
        name="Database Corruption",
        category=RiskCategory.DATA,
        severity=Severity.CRITICAL,
        description="Article IV violation: DuckDB database file corrupted",
        prevention=DatabaseCorruptionRisk().prevent,
        detection=DatabaseCorruptionRisk().detect,
        response=DatabaseCorruptionRisk().respond,
        recovery=DatabaseCorruptionRisk().recover
    )
    if db_corruption_risk.name not in registered:
        enforcer.register_risk(db_corruption_risk)

    performance_risk = Risk(
        name="Performance Budget Exceeded",
        category=RiskCategory.PERFORMANCE,
        severity=Severity.HIGH,
        description="Article IV violation: Performance budget (memory/disk) exceeded",
        prevention=PerformanceBudgetRisk().prevent,
        detection=PerformanceBudgetRisk().detect,
        response=PerformanceBudgetRisk().respond,
        recovery=PerformanceBudgetRisk().recover
    )
    if performance_risk.name not in registered:
        enforcer.register_risk(performance_risk)

def prevent_code_injection():
    """Code Injection 예방"""
    from packs.development.code_validator import CodeValidator
    logger.debug("Code injection prevention active")


def detect_code_injection() -> bool:
    """Code Injection 감지"""
    try:
        from packs.development.code_validator import CodeValidator

        # 최근 생성된 파일 스캔 (protocols, core)
        suspicious_files = []

        for pattern in ["protocols/**/*.py", "core/**/*.py"]:
            for py_file in Path(".").glob(pattern):
                # 최근 1시간 내 수정된 파일만
                import time
                if (time.time() - py_file.stat().st_mtime) < 3600:
                    try:
                        is_safe, reason = CodeValidator.validate_file(py_file)
                        if not is_safe:
                            suspicious_files.append((py_file, reason))
                            logger.warning(f"Unsafe code in {py_file}: {reason}")
                    except Exception as e:
                        logger.debug(f"Could not validate {py_file}: {e}")

        return len(suspicious_files) > 0
    except Exception as e:
        logger.error(f"Code injection detection error: {e}")
        return False


def respond_to_code_injection():
    """Code Injection 대응"""
    logger.critical("🚨 CODE INJECTION: Quarantining suspicious files")
    raise ConstitutionViolationError(
        "Article II violated: Malicious code detected. "
        "This is a critical security violation."
    )


def recover_from_code_injection():
    """Code Injection 복구"""
    logger.info("Recovering from code injection...")
    # Git에서 마지막 안전 버전으로 복구
    import subprocess
    try:
        subprocess.run(
            ["git", "restore", "protocols/", "core/"],
            check=True,
            capture_output=True
        )
        logger.info("Recovered from Git")
    except Exception as e:
        logger.error(f"Code injection recovery failed: {e}")


code_injection_risk = Risk(
    name="Code Injection Attack",
    category=RiskCategory.SECURITY,
    severity=Severity.CRITICAL,
    description="Constitution Article II violation: Malicious code generated by AI",
    prevention=CodeInjectionRisk().prevent,
    detection=CodeInjectionRisk().detect,
    response=CodeInjectionRisk().respond,
    recovery=CodeInjectionRisk().recover
)



# ═══════════════════════════════════════════
# Risk 3: API Rate Limit (Article IV 위반)
# ═══════════════════════════════════════════

def prevent_rate_limit():
    """Rate Limit 예방"""
    from packs.ai.cost_tracker import get_cost_tracker
    tracker = get_cost_tracker()
    logger.debug("Rate limit prevention active")


def detect_rate_limit() -> bool:
    """Rate Limit 감지"""
    try:
        from packs.ai.cost_tracker import get_cost_tracker, CostLimitExceeded

        tracker = get_cost_tracker()

        # 일일 한도 80% 초과 시 경고
        daily_cost = tracker.get_daily_cost()
        if daily_cost > tracker.daily_limit * 0.8:
            logger.warning(f"Rate limit approaching: ${daily_cost:.2f} / ${tracker.daily_limit:.2f}")
            return True

        return False
    except CostLimitExceeded:
        return True
    except Exception as e:
        logger.error(f"Rate limit detection error: {e}")
        return False


def respond_to_rate_limit():
    """Rate Limit 대응"""
    logger.warning("Rate limit approaching: Enabling backoff")
    # retry_with_backoff는 이미 openai_runner에 적용됨
    logger.info("Exponential backoff is active")


def recover_from_rate_limit():
    """Rate Limit 복구"""
    import time
    logger.info("Waiting for rate limit recovery...")
    time.sleep(60)  # 1분 대기
    logger.info("Rate limit recovered")


rate_limit_risk = Risk(
    name="API Rate Limit",
    category=RiskCategory.API,
    severity=Severity.HIGH,
    description="Article IV violation: API rate limit exceeded or approaching",
    prevention=RateLimitRisk().prevent,
    detection=RateLimitRisk().detect,
    response=RateLimitRisk().respond,
    recovery=RateLimitRisk().recover
)



# ═══════════════════════════════════════════
# Risk 4: Database Corruption (Article IV 위반)
# ═══════════════════════════════════════════

def prevent_db_corruption():
    """DB 손상 예방"""
    from protocols.memory.store import MemoryStore
    logger.debug("DB corruption prevention active")


def detect_db_corruption() -> bool:
    """DB 손상 감지"""
    try:
        import duckdb
        from pathlib import Path

        db_path = Path(".autus/memory/memory.db")
        if not db_path.exists():
            return False

        try:
            conn = duckdb.connect(str(db_path))
            # 간단한 무결성 체크
            conn.execute("SELECT COUNT(*) FROM preferences")
            conn.execute("SELECT COUNT(*) FROM patterns")
            conn.execute("SELECT COUNT(*) FROM context")
            conn.close()
            return False
        except Exception as e:
            logger.error(f"DB corruption detected: {e}")
            return True
    except Exception as e:
        logger.error(f"DB corruption detection error: {e}")
        return False


def respond_to_db_corruption():
    """DB 손상 대응"""
    logger.critical("🚨 DATABASE CORRUPTION: Switching to backup")
    # 읽기 전용 모드로 전환
    # 백업 활성화


def recover_from_db_corruption():
    """DB 손상 복구"""
    logger.info("Recovering from database corruption...")

    try:
        from protocols.memory.recovery import RecoveryManager
        from pathlib import Path

        # 최신 체크포인트에서 복구
        checkpoints = RecoveryManager.list_checkpoints()
        if checkpoints:
            RecoveryManager.restore_from_checkpoint(
                checkpoints[0],
                Path(".autus/memory/memory.db")
            )
            logger.info("Recovered from checkpoint")
        else:
            logger.warning("No checkpoint available for recovery")
    except Exception as e:
        logger.error(f"DB recovery failed: {e}")


db_corruption_risk = Risk(
    name="Database Corruption",
    category=RiskCategory.DATA,
    severity=Severity.CRITICAL,
    description="Article IV violation: DuckDB database file corrupted",
    prevention=DatabaseCorruptionRisk().prevent,
    detection=DatabaseCorruptionRisk().detect,
    response=DatabaseCorruptionRisk().respond,
    recovery=DatabaseCorruptionRisk().recover
)



# ═══════════════════════════════════════════
# Risk 5: Performance Budget Exceeded (Article IV 위반)
# ═══════════════════════════════════════════

def prevent_performance_violation():
    """성능 예산 위반 예방"""
    from packs.security.performance import PerformanceBudget
    logger.debug("Performance budget monitoring active")


def detect_performance_violation() -> bool:
    """성능 예산 위반 감지"""
    try:
        from packs.security.performance import PerformanceBudget

        # 메모리 체크
        memory_mb = PerformanceBudget.check_memory_usage()
        if memory_mb and memory_mb > PerformanceBudget.MEMORY_MAX:
            logger.warning(f"Memory budget exceeded: {memory_mb:.1f}MB > {PerformanceBudget.MEMORY_MAX}MB")
            return True

        # 디스크 체크
        disk_free = PerformanceBudget.check_disk_usage()
        if disk_free and disk_free < PerformanceBudget.DISK_MAX:
            logger.warning(f"Disk space low: {disk_free:.1f}MB < {PerformanceBudget.DISK_MAX}MB")
            return True

        return False
    except Exception as e:
        logger.error(f"Performance violation detection error: {e}")
        return False


def respond_to_performance_violation():
    """성능 예산 위반 대응"""
    logger.warning("⚠️ Performance budget exceeded: Enabling resource limits")
    # 리소스 제한 활성화
    # 불필요한 프로세스 종료


def recover_from_performance_violation():
    """성능 예산 위반 복구"""
    logger.info("Recovering from performance violation...")
    # 캐시 정리
    # 리소스 해제
    import gc
    gc.collect()
    logger.info("Performance recovered")


performance_risk = Risk(
    name="Performance Budget Exceeded",
    category=RiskCategory.PERFORMANCE,
    severity=Severity.HIGH,
    description="Article IV violation: Performance budget (memory/disk) exceeded",
    prevention=PerformanceBudgetRisk().prevent,
    detection=PerformanceBudgetRisk().detect,
    response=PerformanceBudgetRisk().respond,
    recovery=PerformanceBudgetRisk().recover
)

