import React from 'react';
import { COLORS } from './types';

// ============================================
// STYLES
// ============================================
export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    display: 'flex',
    height: '100%',
    width: '100%',
    backgroundColor: COLORS.bgPrimary,
    color: COLORS.white,
    overflow: 'hidden',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  leftPanel: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    padding: '24px 32px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  logo: {
    fontSize: '14px',
    fontWeight: 600,
    letterSpacing: '3px',
    color: COLORS.cyan,
  },
  statsRow: {
    display: 'flex',
    gap: '20px',
    marginLeft: '32px',
  },
  statItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    color: COLORS.gray400,
  },
  statDot: {
    width: '8px',
    height: '8px',
    borderRadius: '50%',
  },
  stabilityLabel: {
    fontSize: '10px',
    letterSpacing: '2px',
    color: COLORS.gray600,
  },
  stabilityValue: {
    fontSize: '36px',
    fontWeight: 300,
    color: COLORS.green,
  },
  mapContainer: {
    flex: 1,
    position: 'relative' as const,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bgGrid: {
    position: 'absolute' as const,
    inset: 0,
    backgroundImage: `
      radial-gradient(circle at center, rgba(0, 212, 255, 0.03) 0%, transparent 70%),
      linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px),
      linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px)
    `,
    backgroundSize: '100% 100%, 60px 60px, 60px 60px',
    pointerEvents: 'none' as const,
  },
  orbitalRing: {
    position: 'absolute' as const,
    border: '1px solid rgba(255,255,255,0.05)',
    borderRadius: '50%',
  },
  connectionsSvg: {
    position: 'absolute' as const,
    width: '500px',
    height: '500px',
    pointerEvents: 'none' as const,
  },
  nodesContainer: {
    position: 'absolute' as const,
    width: '500px',
    height: '500px',
  },
  core: {
    position: 'absolute' as const,
    width: '90px',
    height: '90px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #00d4ff 0%, #0088cc 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    zIndex: 10,
    boxShadow: '0 0 60px rgba(0,212,255,0.4), 0 0 120px rgba(0,212,255,0.2), inset 0 0 30px rgba(255,255,255,0.1)',
    transition: 'transform 0.5s ease',
  },
  coreLabel: {
    fontSize: '16px',
    fontWeight: 600,
    color: COLORS.white,
  },
  rightPanel: {
    width: '380px',
    minWidth: '380px',
    backgroundColor: COLORS.bgSecondary,
    borderLeft: '1px solid rgba(255,255,255,0.05)',
    display: 'flex',
    flexDirection: 'column' as const,
    overflow: 'hidden',
  },
  panelContent: {
    flex: 1,
    overflowY: 'auto' as const,
  },
  emptyState: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column' as const,
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px',
    textAlign: 'center' as const,
  },
  emptyIcon: {
    fontSize: '48px',
    opacity: 0.5,
    marginBottom: '16px',
  },
  emptyTitle: {
    fontSize: '18px',
    fontWeight: 500,
    marginBottom: '8px',
  },
  emptyDesc: {
    fontSize: '14px',
    color: COLORS.gray500,
    lineHeight: 1.6,
  },
  detailHeader: {
    padding: '24px',
    borderBottom: '1px solid rgba(255,255,255,0.05)',
  },
  detailTitle: {
    fontSize: '10px',
    letterSpacing: '2px',
    color: COLORS.gray600,
    marginBottom: '8px',
  },
  detailName: {
    fontSize: '24px',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  detailMeta: {
    fontSize: '14px',
    color: COLORS.gray400,
    marginTop: '4px',
  },
  quickStats: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    borderBottom: '1px solid rgba(255,255,255,0.05)',
  },
  quickStat: {
    padding: '16px',
    textAlign: 'center' as const,
    borderRight: '1px solid rgba(255,255,255,0.05)',
  },
  quickStatValue: {
    fontSize: '24px',
    fontWeight: 600,
  },
  quickStatLabel: {
    fontSize: '10px',
    color: COLORS.gray600,
    letterSpacing: '1px',
  },
  section: {
    padding: '20px 24px',
    borderBottom: '1px solid rgba(255,255,255,0.05)',
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '14px',
  },
  sectionIcon: {
    width: '28px',
    height: '28px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
  },
  sectionTitle: {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '1px',
    color: COLORS.gray400,
  },
  tagsContainer: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    gap: '8px',
  },
  tag: {
    padding: '8px 14px',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: '8px',
    fontSize: '13px',
    border: '1px solid rgba(255,255,255,0.05)',
  },
  actionItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '14px 16px',
    borderRadius: '12px',
    marginBottom: '10px',
    cursor: 'pointer',
    border: '1px solid rgba(255,255,255,0.05)',
    backgroundColor: 'rgba(255,255,255,0.03)',
    transition: 'all 0.3s ease',
  },
  actionCheck: {
    width: '20px',
    height: '20px',
    borderRadius: '6px',
    border: '2px solid rgba(255,255,255,0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
  },
  actionText: {
    flex: 1,
    fontSize: '14px',
  },
  actionImpact: {
    fontSize: '14px',
    fontWeight: 500,
    color: COLORS.green,
  },
  directionButtons: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '8px',
  },
  directionBtn: {
    padding: '12px',
    border: '1px solid rgba(255,255,255,0.1)',
    backgroundColor: 'transparent',
    color: COLORS.gray400,
    borderRadius: '10px',
    fontSize: '12px',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  todoSection: {
    backgroundColor: COLORS.bgPrimary,
    borderTop: '1px solid rgba(255,255,255,0.05)',
    padding: '20px 24px',
    maxHeight: '250px',
    overflowY: 'auto' as const,
  },
  todoHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '14px',
  },
  todoTitle: {
    fontSize: '11px',
    fontWeight: 600,
    letterSpacing: '1px',
    color: COLORS.cyan,
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  todoCount: {
    backgroundColor: COLORS.cyan,
    color: '#000',
    padding: '2px 8px',
    borderRadius: '10px',
    fontSize: '11px',
    fontWeight: 600,
  },
  todoClear: {
    fontSize: '11px',
    color: COLORS.gray600,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
  },
  todoList: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '8px',
  },
  todoEmpty: {
    textAlign: 'center' as const,
    padding: '24px',
    color: COLORS.gray600,
    fontSize: '13px',
  },
  todoItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 14px',
    backgroundColor: 'rgba(18,18,26,0.7)',
    borderRadius: '10px',
    border: '1px solid rgba(255,255,255,0.05)',
  },
  todoCheckbox: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    border: '2px solid rgba(255,255,255,0.2)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    flexShrink: 0,
  },
  todoInfo: {
    flex: 1,
    minWidth: 0,
  },
  todoText: {
    fontSize: '13px',
  },
  todoSource: {
    fontSize: '11px',
    color: COLORS.gray600,
  },
  todoRemove: {
    background: 'none',
    border: 'none',
    color: COLORS.gray600,
    cursor: 'pointer',
    padding: '4px',
    fontSize: '16px',
  },
};
