/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * AUTUS ExecutorView - 실행자(K1~K2) 뷰
 * "생각하지 않게 한다. 다음 행동만 보여준다."
 * ═══════════════════════════════════════════════════════════════════════════════
 */

import React, { useState, useEffect } from 'react';
import { 
  NextActionCard, 
  AutoReportCard, 
  RiskAlertCard,
  TaskDeletedCard,
  type NextAction 
} from '../../cards';

// ═══════════════════════════════════════════════════════════════════════════════
// Mock Data (실제 구현에서는 API 연동)
// ═══════════════════════════════════════════════════════════════════════════════

const MOCK_ACTIONS: NextAction[] = [
  {
    id: '1',
    task: '철근 배근 (구간 A)',
    standard: '200mm 간격',
    status: 'in_progress',
    warning: '간격 230mm 감지 - 조정 필요',
    metadata: {
      location: 'A동 3층',
      priority: 'high',
    },
  },
  {
    id: '2',
    task: '콘크리트 타설 준비',
    standard: 'KS F 4009 기준',
    status: 'pending',
    metadata: {
      location: 'A동 2층',
      deadline: '14:00',
    },
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// Component
// ═══════════════════════════════════════════════════════════════════════════════

type ViewState = 'action' | 'report' | 'risk' | 'deleted';

const ExecutorView: React.FC = () => {
  const [viewState, setViewState] = useState<ViewState>('action');
  const [currentAction, setCurrentAction] = useState<NextAction>(MOCK_ACTIONS[0]);
  const [riskAlert, setRiskAlert] = useState<{
    type: 'mistake' | 'safety';
    message: string;
  } | null>(null);

  // 위험 경고 시뮬레이션 (ENGINE B)
  useEffect(() => {
    if (currentAction.warning) {
      setRiskAlert({
        type: 'safety',
        message: currentAction.warning,
      });
      setViewState('risk');
    }
  }, [currentAction]);

  const handleContinue = async (actionId: string) => {
    console.log('Continue action:', actionId);
    // API 호출 후 다음 작업으로 이동
    setViewState('action');
    setRiskAlert(null);
  };

  const handleComplete = async (actionId: string) => {
    console.log('Complete action:', actionId);
    // 완료 후 자동 보고서 생성
    setViewState('report');
  };

  const handleReportConfirm = () => {
    // 다음 작업으로 이동
    const nextIndex = MOCK_ACTIONS.findIndex(a => a.id === currentAction.id) + 1;
    if (nextIndex < MOCK_ACTIONS.length) {
      setCurrentAction(MOCK_ACTIONS[nextIndex]);
    }
    setViewState('action');
  };

  const handleRiskAcknowledge = () => {
    setRiskAlert(null);
    setViewState('action');
  };

  // ─────────────────────────────────────────────────────────────────────────
  // Render
  // ─────────────────────────────────────────────────────────────────────────

  // 위험 경고 화면
  if (viewState === 'risk' && riskAlert) {
    return (
      <RiskAlertCard
        riskType={riskAlert.type}
        message={riskAlert.message}
        suggestion="기준에 맞게 간격을 조정한 후 계속하세요"
        onAcknowledge={handleRiskAcknowledge}
      />
    );
  }

  // 자동 보고서 화면
  if (viewState === 'report') {
    return (
      <AutoReportCard
        reportId="RPT-001"
        photoCount={6}
        workDuration="2시간 15분"
        autoGenerated={true}
        onConfirm={handleReportConfirm}
      />
    );
  }

  // 업무 삭제 알림 화면
  if (viewState === 'deleted') {
    return (
      <TaskDeletedCard
        taskName="일일 점검 보고서 작성"
        reason="자동화 시스템으로 대체되었습니다"
        onConfirm={() => setViewState('action')}
      />
    );
  }

  // 기본 - 다음 작업 화면
  return (
    <NextActionCard
      action={currentAction}
      onContinue={handleContinue}
      onComplete={handleComplete}
    />
  );
};

export default ExecutorView;
