# AUTUS Data Flow Specification
# L0-L1-L2-L3 Data Level Architecture

version: "1.0.0"
source: "Apple Privacy-by-Architecture"

# ============================================
# DATA LEVELS
# ============================================
data_levels:
  L0:
    name: "Raw Data"
    description: "원본 데이터 - 디바이스에서 절대 이동 불가"
    policy: "NEVER_LEAVE_DEVICE"
    encryption: "AES-256-GCM"
    storage: "device_only"
    retention: "user_controlled"
    examples:
      - "Raw sensor data"
      - "Original user input"
      - "Unprocessed events"
      - "Private keys / seeds"
    
  L1:
    name: "Local Processed"
    description: "로컬 1차 가공 데이터 - 사용자 소유"
    policy: "USER_OWNED"
    encryption: "AES-256-GCM"
    storage: "~/.autus.memory.yaml"
    retention: "user_controlled"
    examples:
      - "Preferences"
      - "Patterns"
      - "Workflows"
      - "Consent records"
    
  L2:
    name: "Summary Data"
    description: "요약 데이터 - 서버 전송 허용"
    policy: "SERVER_ALLOWED"
    encryption: "TLS 1.3"
    storage: "server_optional"
    retention: "30_days"
    examples:
      - "Aggregated statistics"
      - "Anonymized patterns"
      - "Model gradients"
      - "Compressed vectors"
    
  L3:
    name: "Metrics Data"
    description: "지표 데이터 - 서버 전송 허용"
    policy: "SERVER_ALLOWED"
    encryption: "TLS 1.3"
    storage: "server"
    retention: "90_days"
    examples:
      - "KPI values"
      - "System health"
      - "Usage metrics"
      - "Performance data"

# ============================================
# DATA FLOW PIPELINES
# ============================================
pipelines:
  sovereign_flow:
    name: "Sovereign Memory Flow"
    description: "로컬 데이터 처리 파이프라인"
    steps:
      - step: 1
        name: "Capture"
        input: "User action"
        output: "L0 raw event"
        location: "device"
      - step: 2
        name: "Process"
        input: "L0 raw event"
        output: "L1 processed data"
        location: "device"
        operation: "local_compute"
      - step: 3
        name: "Store"
        input: "L1 processed data"
        output: "Memory file"
        location: "device"
        file: "~/.autus.memory.yaml"

  federated_flow:
    name: "Federated Learning Flow"
    description: "분산 학습 파이프라인 (Google Spec)"
    steps:
      - step: 1
        name: "Local Train"
        input: "L1 local data"
        output: "Local gradient"
        location: "device"
      - step: 2
        name: "Compress"
        input: "Local gradient"
        output: "Compressed gradient"
        location: "device"
        compression_ratio: 0.90
      - step: 3
        name: "Noise Inject"
        input: "Compressed gradient"
        output: "Private gradient"
        location: "device"
        method: "differential_privacy"
        epsilon: 1.0
      - step: 4
        name: "Transmit"
        input: "Private gradient"
        output: "L2 summary"
        location: "network"
      - step: 5
        name: "Aggregate"
        input: "L2 summaries"
        output: "Global model"
        location: "server"

  event_flow:
    name: "Reality Event Flow"
    description: "이벤트 압축 파이프라인 (Tesla Spec)"
    steps:
      - step: 1
        name: "Ingest"
        input: "Raw event"
        output: "L0 event"
        location: "device"
      - step: 2
        name: "Window"
        input: "L0 events"
        output: "Event batch"
        location: "device"
        windows: ["1s", "5s", "30s"]
      - step: 3
        name: "Compress"
        input: "Event batch"
        output: "Vector summary"
        location: "device"
        compression_ratio: 0.90
      - step: 4
        name: "Update Graph"
        input: "Vector summary"
        output: "Graph node update"
        location: "device"
      - step: 5
        name: "Sync"
        input: "L2 graph delta"
        output: "Server graph"
        location: "server"
        optional: true

  impact_flow:
    name: "Impact Prediction Flow"
    description: "영향 예측 파이프라인 (ByteDance Spec)"
    steps:
      - step: 1
        name: "Embed"
        input: "User, Pack, Event"
        output: "Dense vectors"
        location: "device"
        dimensions: 128
      - step: 2
        name: "Predict"
        input: "Dense vectors + Context"
        output: "Impact predictions"
        location: "device"
        latency_ms: 30
      - step: 3
        name: "Rank"
        input: "Predictions"
        output: "Ranked actions"
        location: "device"
      - step: 4
        name: "Feedback"
        input: "User response"
        output: "Model update"
        location: "device"
        interval: "1min"

# ============================================
# SECURITY REQUIREMENTS
# ============================================
security:
  encryption:
    at_rest:
      algorithm: "AES-256-GCM"
      key_storage: "device_secure_enclave"
    in_transit:
      algorithm: "TLS 1.3"
      certificate: "pinned"
  
  access_control:
    L0: "device_only"
    L1: "user_only"
    L2: "user_consent_required"
    L3: "aggregated_anonymous"
  
  audit:
    enabled: true
    retention: "365_days"
    location: "device"

# ============================================
# COMPLIANCE
# ============================================
compliance:
  gdpr:
    right_to_access: true
    right_to_delete: true
    data_portability: true
    consent_management: true
  
  privacy_by_design:
    minimize_data: true
    local_first: true
    encryption_default: true
    user_control: true

# ============================================
# KPIs
# ============================================
kpis:
  raw_data_leakage: 0
  device_compute_latency_ms: 150
  privacy_audit_pass_rate: 1.0
  compression_ratio: 0.90
  model_improvement_rate: 0.10
  privacy_loss_epsilon: 1.0
