
import yaml
from pathlib import Path

SPEC = Path('docs/specs/SPEC-1D-emo_hub_objects.yaml')

def generate_models():
    data = yaml.safe_load(open(SPEC))
    ents = data['entities']

    out = ['# AUTOGENERATED
from pydantic import BaseModel
']

    for ent in ents:
        out.append(f'class {ent[name]}(BaseModel):')
        for attr in ent['attributes']:
            name = attr['name']
            t = attr['type'].split('.')[0]
            out.append(f'    {name}: str  # TODO: map {t}')
        out.append('')

    Path('packs/autogen_emo_models.py').write_text('
'.join(out))

if __name__ == '__main__':
    generate_models()

