#!/usr/bin/env bash
# AUTUS v3.0 autogen v4 (skeleton)
# 사용법: ./scripts/autus_autogen.sh <CELL_NAME>
set -euo pipefail
CELL_NAME="${1:-}"
if [ -z "$CELL_NAME" ]; then
  echo "[ERROR] CELL_NAME required"
  exit 1
fi
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CELLS_DIR="$ROOT/docs/cells"
PACKS_DIR="$ROOT/packs"
TESTS_DIR="$ROOT/tests"
DOCS_DIR="$ROOT/docs/packs"
ROUTES_DIR="$ROOT/server/routes"
REGISTRY_DIR="$ROOT/core/registry"
mkdir -p "$CELLS_DIR" "$PACKS_DIR" "$TESTS_DIR" "$DOCS_DIR" "$ROUTES_DIR" "$REGISTRY_DIR"
CELL_FILE="$CELLS_DIR/${CELL_NAME}.json"
if [ ! -f "$CELL_FILE" ]; then
  echo "[WARN] Cell JSON not found, creating minimal stub: $CELL_FILE"
  cat > "$CELL_FILE" << EOF_CELL
{
  "name": "${CELL_NAME}",
  "description": "Auto-generated cell stub for ${CELL_NAME}",
  "target_axis": "self_gen",
  "inputs": [],
  "outputs": []
}
EOF_CELL
fi
PACK_FILE="$PACKS_DIR/${CELL_NAME}_autogen.py"
TEST_FILE="$TESTS_DIR/test_${CELL_NAME}.py"
DOC_FILE="$DOCS_DIR/${CELL_NAME}.md"
ROUTE_FILE="$ROUTES_DIR/${CELL_NAME}.py"
echo "[AUTUS] Generating pack/test/doc/router for cell: ${CELL_NAME}"
cat > "$PACK_FILE" << EOF_PY
# AUTO-GENERATED BY AUTUS (DO NOT EDIT)
from typing import Any, Dict
from core.runtime.controller import RuntimeController
def run(controller: RuntimeController, payload: Dict[str, Any]) -> Dict[str, Any]:
    """Entry point for pack '${CELL_NAME}'."""
    return {
        "status": "ok",
        "cell": "${CELL_NAME}",
        "payload": payload,
    }
EOF_PY
cat > "$TEST_FILE" << EOF_TEST
# AUTO-GENERATED TEST (DO NOT EDIT)
from fastapi.testclient import TestClient
from server.main import app
client = TestClient(app)
def test_${CELL_NAME}_endpoint():
    resp = client.post("/pack/${CELL_NAME}", json={"payload": {"ping": "pong"}})
    assert resp.status_code == 200
EOF_TEST
cat > "$DOC_FILE" << EOF_MD
# Pack: ${CELL_NAME}
- Source cell: docs/cells/${CELL_NAME}.json
- Generated by: scripts/autus_autogen.sh
## Description
TBD – will be filled by AUTUS autogen pipeline.
EOF_MD
cat > "$ROUTE_FILE" << EOF_ROUTE
from fastapi import APIRouter
from typing import Any, Dict
from core.runtime.controller import RuntimeController
from packs.${CELL_NAME}_autogen import run as pack_run
router = APIRouter()
@router.post("/pack/${CELL_NAME}")
async def run_${CELL_NAME}(payload: Dict[str, Any]) -> Dict[str, Any]:
    controller = RuntimeController()
    return pack_run(controller, payload)
EOF_ROUTE
echo "[AUTUS] DONE: $PACK_FILE, $TEST_FILE, $DOC_FILE, $ROUTE_FILE"
