"""
AUTUS Logging System
Generated by: AUTUS Meta-Circular Development
Date: 2024-11-23
"""

import logging
import sys
from typing import Optional
from pathlib import Path

class AUTUSLogger:
    """
    Centralized logging system for AUTUS
    
    Features:
    - Console and file logging
    - Different log levels
    - Structured log format
    """
    
    def __init__(
        self, 
        name: str = "autus",
        level: int = logging.INFO,
        log_file: Optional[Path] = None
    ):
        """
        Initialize AUTUS logger
        
        Parameters
        ----------
        name : str
            Logger name
        level : int
            Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
        log_file : Optional[Path]
            Path to log file (None = console only)
        """
        self.logger = logging.getLogger(name)
        self.logger.setLevel(level)
        
        # Clear existing handlers
        self.logger.handlers.clear()
        
        # Console handler
        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setLevel(level)
        
        # Format
        formatter = logging.Formatter(
            '%(asctime)s - %(name)s - %(levelname)s - %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        console_handler.setFormatter(formatter)
        self.logger.addHandler(console_handler)
        
        # File handler (if specified)
        if log_file:
            log_file.parent.mkdir(parents=True, exist_ok=True)
            file_handler = logging.FileHandler(log_file)
            file_handler.setLevel(level)
            file_handler.setFormatter(formatter)
            self.logger.addHandler(file_handler)
    
    def debug(self, message: str) -> None:
        """Log debug message"""
        self.logger.debug(message)
    
    def info(self, message: str) -> None:
        """Log info message"""
        self.logger.info(message)
    
    def warning(self, message: str) -> None:
        """Log warning message"""
        self.logger.warning(message)
    
    def error(self, message: str) -> None:
        """Log error message"""
        self.logger.error(message)
    
    def critical(self, message: str) -> None:
        """Log critical message"""
        self.logger.critical(message)

# Demo
if __name__ == "__main__":
    logger = AUTUSLogger("demo")
    
    logger.info("✅ AUTUS Logger initialized")
    logger.info("📝 Logging system working!")
    logger.debug("Debug message")
    logger.warning("⚠️  Warning message")
    logger.error("❌ Error message (demo)")
    
    print("\n✅ Logger working perfectly!")
