MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]






MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]






MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]






MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]






MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]
















MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]






MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]






MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]






MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]






MONEY_EVENT_TYPES = {
    "CASH_IN",
    "CONTRACT_SIGNED",
    "INVEST_CONFIRMED",
    "COST_SAVED",
    "MRR",
    "REFERRAL_TO_CONTRACT",
    # Optional ops events (if used)
    "DELIVERY_COMPLETE",
    "INVOICE_ISSUED",
}

RECO_TYPES = {"DIRECT_DRIVEN", "INDIRECT_DRIVEN", "MIXED", ""}

BURN_TYPES = {"LOSS_TIME", "DELAY", "REWORK", "MEETING", "PREVENTED", "FIXED"}

ROLE_ENUM = ["RAINMAKER", "CLOSER", "OPERATOR", "BUILDER", "CONNECTOR", "CONTROLLER"]






















